[py2py3] Migration at level scr/python/A/B/C - slice 5
dmwm/WMCore pull request #10262
Opened 2021-02-04 16:41 UTC by mapellidario

Fixes #10116 

#### Status

In development

#### Related PRs

* Previous migration PR: #10165 (slice4, issue #10115  )
* Next migration PR: _noot open yet_ (slice6, issue  #10131 )

#### Description

Run futurize and some manual changes on the first batch of src/python/A/B/C.

I decided to use the "native string" approach and not force to use `from builtins import str` extensively when not needed. We will see how it goes. This has the advantage of reducing migration effort and without messing with strings when it is not really needed.
This may cause troubles only in:
* `src/python/WMCore/WMBS/Fileset.py ` (to be tested in py3, topen an issue to track this)

#### Is it backward compatible (if not, which system it affects?)

It should be!

#### External dependencies / deployment changes

no changes

2021-02-05 11:13 UTC, mapellidario commented
test this, please

2021-02-08 07:01 UTC, amaltaro requested changes
Dario, code looks good in general. I have made a few comments along the code though to be taken into consideration.

You mention about Fileset.py in the PR description, but I haven't seen any changes made to that module. Did I miss anything?

One more question/request, could you please check those WMBS/* modules against your oracle jenkins setup?

2021-02-09 09:45 UTC, mapellidario commented on src/python/WMCore/WMSpec/Persistency.py
> +from urllib.request import urlopen, Request
You are right! this is going to break cPickle support!
It felt a bit spooky to me that we missed the modernization of this file and the answer was in #9762 PR description! shame on me that simply assumed it was an error of Dario-of-the-past and did look much into possible cause.

Thanks for trusting that past-me wouldn't have missed a file more than I do!

2021-02-09 10:13 UTC, mapellidario commented on src/python/WMCore/Services/ReqMgr/ReqMgr.py
> +        for name, values in list(queryDict.items()):
Ops, I have no idea how i missed this!

I would stick with `viewitems`, following [this sugestion in future code](https://github.com/PythonCharmers/python-future/blob/4657ad23de79a541ebcc7a06f1b9ad60172ad3c4/src/future/utils/__init__.py#L310). In py3 both `future.utils.viewitems` and `future.utils.iteritms` load `dict.items`, while in py2 they load `viewitems/iteritems` directly.
As for which is the better, stackoverflow insists that they have similar CPU-time performance [here](https://stackoverflow.com/a/23083560) and [here](https://stackoverflow.com/a/10190228). Memory-wise, I have to come up with some tests, but if they were different I assume that they would have stated it clearly [in the docs](https://python-future.org/compatible_idioms.html#dictionaries). I will come up with some tests however!

2021-02-09 10:14 UTC, mapellidario commented on src/python/WMCore/Services/FWJRDB/FWJRDBAPI.py
> +            return list(result.keys())
And again, you re correct! they are exactly the same

2021-02-09 13:36 UTC, amaltaro commented on src/python/WMCore/Services/ReqMgr/ReqMgr.py
> +        for name, values in list(queryDict.items()):
Don't worry about testing their performance Dario. Let's just stick with what we have been using and what's suggested (viewitems)

2021-02-10 11:03 UTC, mapellidario commented
Test this please

2021-02-11 11:44 UTC, mapellidario commented
I run the unit tests in WMBS_t in my VM oracle setup. With this PR I get the same failure as in `master ` there is only one change: `First part of what used to be testRandomCrapForGenerators` does not fail anymore!

I paste here the diff of the unit tests log:

```diff
> diff -u --color unittest_master.txt unittest_pr.txt
--- unittest_master.txt 2021-02-11 12:39:21.711882666 +0100
+++ unittest_pr.txt     2021-02-11 12:39:01.740085287 +0100
@@ -1,4 +1,4 @@
-> python setup.py test --buildBotMode=true --reallyDeleteMyDatabaseAfterEveryTest=true --testCertainPath=test/python/WMCore_t/WMBS_t/        
+> python setup.py test --buildBotMode=true --reallyDeleteMyDatabaseAfterEveryTest=true --testCertainPath=test/python/WMCore_t/WMBS_t/
 running test
 Using the tests below: test/python/WMCore_t/WMBS_t/
 #### WE ARE DELETING YOUR DATABASE. 3 SECONDS TO CANCEL ####
@@ -6,7 +6,7 @@
 We are going to trash databases after every test
 ### We are in buildbot mode ###
 ----------------------------------------------------------------------
-Ran 240 tests in 0.020s
+Ran 240 tests in 0.018s
 
 OK
 path lists is ['test/python/WMCore_t/WMBS_t/']
@@ -54,7 +54,7 @@
 #96 _testLimit_ ... ok
 #97 _testLocationSplit_ ... ok
 #98 _testMoreFiles_ ... ok
-#99 First part of what used to be testRandomCrapForGenerators ... FAIL
+#99 First part of what used to be testRandomCrapForGenerators ... ok
 #107 _testAllAcquired_ ... ok
 #108 _testClosed_ ... ok
 #109 _testClosedSomeAcquired_ ... ok
@@ -353,56 +353,7 @@
 root: DEBUG: Tables for WMCore.WMBS created
 root: INFO: Workflow id 1 created for wf001
 root: INFO: Fileset created: TestFileset
-root: INFO: Fileset created: 9cc299fa-9da2-432f-9cd7-93b8e8cfd410
---------------------- >> end captured logging << ---------------------
-
-======================================================================
-FAIL: First part of what used to be testRandomCrapForGenerators
-----------------------------------------------------------------------
-Traceback (most recent call last):
-  File "/data/cms-dmwm/wmcore_unittest/WMCore/test/python/WMCore_t/WMBS_t/JobSplitting_t/FileBased_t.py", line 515, in testRandomCrap1
-    self.assertEqual(len(jobGroups), 6)
-AssertionError: 8 != 6
--------------------- >> begin captured logging << --------------------
-root: DEBUG: Tables for WMCore.WMBS created
-root: INFO: Fileset created: TestFileset1
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 2}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 3}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 4}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 5}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 6}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 7}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 8}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 9}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 10}]
-root: DEBUG: File.Heritage binds: [{'parent': 1, 'child': 11}]
-root: INFO: Fileset created: TestFileset2
-root: INFO: Fileset created: TestFileset3
-root: INFO: Workflow id 1 created for wf001
-root: DEBUG: Opening DB resultProxies for JobFactory
-root: DEBUG: Received 1 proxies
-root: DEBUG: About to load files by proxy
-root: DEBUG: Loaded 2 files
-root: DEBUG: About to commit 1 jobGroups
-root: DEBUG: About to commit 2 jobs
-root: DEBUG: About to load files by proxy
-root: DEBUG: Loaded 2 files
-root: DEBUG: About to commit 2 jobGroups
-root: DEBUG: About to commit 1 jobs
-root: DEBUG: About to load files by proxy
-root: DEBUG: Loaded 2 files
-root: DEBUG: About to commit 2 jobGroups
-root: DEBUG: About to commit 1 jobs
-root: DEBUG: About to load files by proxy
-root: DEBUG: Loaded 2 files
-root: DEBUG: About to commit 1 jobGroups
-root: DEBUG: About to commit 2 jobs
-root: DEBUG: About to load files by proxy
-root: DEBUG: Loaded 2 files
-root: DEBUG: About to commit 2 jobGroups
-root: DEBUG: About to commit 1 jobs
-root: DEBUG: About to load files by proxy
-root: DEBUG: Loaded 0 files
+root: INFO: Fileset created: 8fa6762c-1b5b-470e-be14-f3b1815ab722
 --------------------- >> end captured logging << ---------------------
 
 ======================================================================
@@ -423,7 +374,7 @@
 restkit.client.request: INFO: Start request: HEAD http://localhost:6994/lumi_t
 restkit.client.request: DEBUG: Request headers: [[u'HEAD /lumi_t HTTP/1.1\r\n', 'Host: localhost:6994\r\n', 'User-Agent: couchapp/0.7.1\r\n', 'Accept-Encoding: None\r\n', 'Accept: application/json\r\n', 'Authorization: Basic dW5pdHRlc3RhZ2VudDpwYXNzd2Q=\r\n', '\r\n']]
 restkit.client.request: DEBUG: Start response: 200 OK
-restkit.client.request: DEBUG: Response headers: [[('Server', 'CouchDB/1.6.1 (Erlang OTP/R16B03-1)'), ('Date', 'Wed, 10 Feb 2021 11:06:40 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '225'), ('Cache-Control', 'must-revalidate')]]
+restkit.client.request: DEBUG: Response headers: [[('Server', 'CouchDB/1.6.1 (Erlang OTP/R16B03-1)'), ('Date', 'Wed, 10 Feb 2021 11:50:12 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '225'), ('Cache-Control', 'must-revalidate')]]
 restkit.client.request: DEBUG: Return response: http://localhost:6994/lumi_t
 couchapp.localdoc: DEBUG: push updates/newgroup.js
 couchapp.localdoc: DEBUG: push updates/newuser.js
@@ -442,7 +393,7 @@
 restkit.client.request: INFO: Start request: GET http://localhost:6994/lumi_t/_design/GroupUser
 restkit.client.request: DEBUG: Request headers: [[u'GET /lumi_t/_design/GroupUser HTTP/1.1\r\n', 'Host: localhost:6994\r\n', 'User-Agent: couchapp/0.7.1\r\n', 'Accept-Encoding: None\r\n', 'Accept: application/json\r\n', 'Authorization: Basic dW5pdHRlc3RhZ2VudDpwYXNzd2Q=\r\n', '\r\n']]
 restkit.client.request: DEBUG: Start response: 404 Object Not Found
-restkit.client.request: DEBUG: Response headers: [[('Server', 'CouchDB/1.6.1 (Erlang OTP/R16B03-1)'), ('Date', 'Wed, 10 Feb 2021 11:06:40 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '41'), ('Cache-Control', 'must-revalidate')]]
+restkit.client.request: DEBUG: Response headers: [[('Server', 'CouchDB/1.6.1 (Erlang OTP/R16B03-1)'), ('Date', 'Wed, 10 Feb 2021 11:50:12 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '41'), ('Cache-Control', 'must-revalidate')]]
 restkit.client.request: DEBUG: Return response: http://localhost:6994/lumi_t/_design/GroupUser
 couchapp.localdoc: DEBUG: attach index.html 
 couchapp.localdoc: DEBUG: attach style/main.css 
@@ -459,14 +410,14 @@
 restkit.client.request: INFO: Start request: PUT http://localhost:6994/lumi_t/_design/GroupUser
 restkit.client.request: DEBUG: Request headers: [[u'PUT /lumi_t/_design/GroupUser HTTP/1.1\r\n', 'Host: localhost:6994\r\n', 'User-Agent: couchapp/0.7.1\r\n', 'Accept-Encoding: None\r\n', 'Accept: application/json\r\n', 'Content-Length: 32028\r\n', 'Content-Type: application/json\r\n', 'Authorization: Basic dW5pdHRlc3RhZ2VudDpwYXNzd2Q=\r\n', '\r\n']]
 restkit.client.request: DEBUG: Start response: 201 Created
-restkit.client.request: DEBUG: Response headers: [[('Server', 'CouchDB/1.6.1 (Erlang OTP/R16B03-1)'), ('Location', 'http://localhost:6994/lumi_t/_design/GroupUser'), ('ETag', '"1-c2e1905c915c668f4395b69025da5746"'), ('Date', 'Wed, 10 Feb 2021 11:06:40 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '80'), ('Cache-Control', 'must-revalidate')]]
+restkit.client.request: DEBUG: Response headers: [[('Server', 'CouchDB/1.6.1 (Erlang OTP/R16B03-1)'), ('Location', 'http://localhost:6994/lumi_t/_design/GroupUser'), ('ETag', '"1-c2e1905c915c668f4395b69025da5746"'), ('Date', 'Wed, 10 Feb 2021 11:50:12 GMT'), ('Content-Type', 'application/json'), ('Content-Length', '80'), ('Cache-Control', 'must-revalidate')]]
 restkit.client.request: DEBUG: Return response: http://localhost:6994/lumi_t/_design/GroupUser
 couchapp.localdoc: INFO: Visit your CouchApp here:
 http://unittestagent:passwd@localhost:6994/lumi_t/_d [...]

2021-02-11 11:51 UTC, mapellidario commented
Regarding `Fileset.py`: you are correct. I did not change it. Maybe I was not too clear in the PR description message. 
In `Fileset.py` we use `str()`, so futurize suggested adding `from builtins import str`. Since I would like to change as little code as possible, especially when dealing with strings, I decided not to listen to such suggestions from futurize unless they seem necessary. In this case, I think we are in a good shape not adding anything, but I am not so sure. So, for future-me I added a comment in the PR description mentioning that I willingly did not include such change, betting it will not cause us any problem

2021-02-11 11:53 UTC, mapellidario commented on src/python/WMCore/WMSpec/Persistency.py
> +from urllib.request import urlopen, Request
I added a new commit in which we import only urllib from the future backports of the standard library, not affeting pickle/cPickle

2021-02-11 11:54 UTC, mapellidario commented on src/python/WMCore/Services/ReqMgr/ReqMgr.py
> +        for name, values in list(queryDict.items()):
Changes added in new commit!

2021-02-15 20:21 UTC, amaltaro commented
@mapellidario Dario, if you are no longer working on this PR, can you please squash the src code changes in one commit, and pylint + unit tests in another commit?

It looks good to go from my side (to keep an eye out for those changes in the Persistency module though).

2021-02-15 21:25 UTC, mapellidario commented
Reabes onto `master` and squashed. Thanks again!

2021-02-16 08:19 UTC, merged