Split initial data fethig steps && Return from handled exceptions.
dmwm/WMCore pull request #10762
Opened 2021-08-19 11:25 UTC by todor-ivanov

Fixes #10758 
 
#### Status
Ready

#### Description
In order to properly handle all possible situations with an eventual empty or missing `protectedLFNs` list we need to split the steps for fetching of the initial data needed for the service to run and also to return from handled exceptions instead of continuing the cycle .   

#### Is it backward compatible (if not, which system it affects?)
YES 

#### Related PRs
None

#### External dependencies / deployment changes
None

2021-08-19 15:46 UTC, amaltaro requested changes
These changes look pretty good to me, Todor. I have only one suggestion on the logging level, comment made along the code.

2021-08-19 15:46 UTC, amaltaro commented on src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
> +                self.logger.info(msg)
I'd suggest to set it to error, since it causes the cycle execution to be skipped.

2021-08-19 15:46 UTC, amaltaro commented on src/python/WMCore/MicroService/MSUnmerged/MSUnmerged.py
> +                self.logger.info(msg)
Same here, I'd set it to error level

2021-08-20 08:39 UTC, todor-ivanov commented
Thanks  @amaltaro. it is done now.

2021-08-20 11:30 UTC, amaltaro approved these changes
Thanks for applying those changes, Todor.

2021-08-20 11:30 UTC, merged