Prevent cache clearing in ReqMgrAux API
dmwm/WMCore pull request #11033
Opened 2022-03-10 15:16 UTC by goughes

Fixes #10860 

#### Status
Not tested

#### Description
Updates the `_getResult` method of the ReqMgrAux API to not clear its disk cache by default. Also, sets a 1 minute cache duration for agent polling threads to prevent multiple queries.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
NA

#### External dependencies / deployment changes
NA

2022-03-18 10:07 UTC, amaltaro requested changes
Erik, these changes look good to me. However, I would suggest a small variation of this as follows:
* I think we can default this cache to 5min, for all those components
* create a new `General` WMAgent configuration attribute which will contain the cache duration, e.g. something like `config.General.ReqMgrAuxCacheDuration = 0.083 (please add a comment explaining this valid and unit)
*  read this value in from the components with a default value, e.g. `var = getattr(config.General, "ReqMgrAuxCacheDuration", 5 / 60)`, such that it doesn't fail unit tests.

Here is the place to change this configuration: https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L93

2022-03-24 23:03 UTC, amaltaro approved these changes
This looks good to me, thanks Erik! Could you please squash these commits? Thanks

2022-03-25 14:23 UTC, goughes commented
Got these squashed, thanks @amaltaro!

2022-03-25 15:36 UTC, amaltaro commented
Thanks Erik!

2022-03-25 15:36 UTC, merged