Add usage of gzip encoding via DBS_GZIP_ENCODING env
dmwm/WMCore pull request #11056
Opened 2022-03-28 19:19 UTC by vkuznet

Fixes #11055

#### Status
not-tested

#### Description
Add ability to use gzip encoding when uploading data to DBS server

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
<If it's a follow up work; or porting a fix from a different branch, please mention them here.>

#### External dependencies / deployment changes
Requires new DBSClient, version 4.0.7 or above.

2022-03-28 19:42 UTC, amaltaro requested changes
Valentin, thanks for the prompt feedback and action on this item.
However, the right way to deal with it is by defining a new component parameter in our default configuration:
https://github.com/dmwm/WMCore/blob/master/etc/WMAgentConfig.py#L147

which is then picked up in this component from the Configuration object.

2022-03-29 09:50 UTC, todor-ivanov requested changes
Thanks @vkuznet 
I'd second Alan's suggestion. it would be better to stick to configuration parameters going through the configuration module rather than through environment variables.

2022-03-29 13:03 UTC, vkuznet commented
ok, now you have as configuration parameter

2022-03-29 13:09 UTC, todor-ivanov approved these changes
Thanks @vkuznet  for the prompt fix!
This looks good to me!

2022-03-29 18:35 UTC, vkuznet commented
Alan, the failed unit test `[E1123, line 202 in DBSUploadPoller.__init__: Unexpected keyword argument 'gzip' in constructor call]()` implies that on jenkins you don't have newer version of dbsClient. As I provided in description of this ticket the version 4.0.7 or above is required. Could you please check and post here which version of dbsClient is used in jenkins and if necessary upgrade it to recent version.

2022-03-29 18:42 UTC, amaltaro commented
Jenkins has WMAgent `2.0.1`, which is the same what we have in the docker image. Looking into the container, I see version 4.0.7 in there:
```
[dmwm@7de784512c7b WMArchive_t]$ ls /home/dmwm/unittestdeploy/wmagent/current/sw/slc7_amd64_gcc630/cms/py3-dbs3-client/4.0.7/
```

2022-03-29 18:48 UTC, vkuznet commented
ok, thanks, I found the issue.

2022-03-31 13:53 UTC, amaltaro requested changes
Valentin, this looks good in general, but I left a couple of suggestions along the code
Could you please update the initial description as well (and state that it requires Go-based DBSWriter before this new feature can be enabled)? Thanks

2022-03-31 13:53 UTC, amaltaro commented on src/python/WMComponent/DBS3Buffer/DBSUploadPoller.py
> +        self.dbsApi = DbsApi(url=self.dbsUrl, useGzip=self.gzipEncoding)
@vkuznet Valentin, it looks like we do not need to use gzip when getting this instance. It's only used for checking whether a block exists in the DBS server. I'd say not using it for this use case will reduce the overall latency for such checks (no need to compress before and after send).

2022-03-31 13:53 UTC, amaltaro commented on etc/WMAgentConfig.py
> +config.DBS3Upload.gzipEncoding = False # swith to True when new DBSWriter will be in place
typo. And how about documenting it like "set DbsApi requests to use gzip enconding, thus sending compressed data"?

2022-03-31 13:53 UTC, amaltaro commented on src/python/WMQuality/Emulators/DBSClient/DBS3API.py
> +        :param kwds: optional positional DBSApi parameters which are irrelevant
these are actually keyword arguments.

2022-03-31 14:48 UTC, vkuznet commented
Alan, I adjusted code based on your feedback. Tests are fine. It is ready for review again.

2022-03-31 20:08 UTC, amaltaro approved these changes
Looks good to me, thanks!

2022-03-31 20:09 UTC, merged