move ckey/cert functions to Utils.CertTools
dmwm/WMCore pull request #11101
Opened 2022-04-18 19:01 UTC by vkuznet

Partially Fixes #11098 (moving cert/ceky function will allow to share code between MicroServices and DBS services)

#### Status
ready

#### Description
Move functions `ckey` and `cert` into `Utils.CertTools` which is generic place to import from other places. This will allow to share and use this code in different Services, like MicroServices and DBS.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
See #11099 , if applied then I can safely remove these functions from #11099  and use common code.

#### External dependencies / deployment changes

2022-04-18 21:19 UTC, vkuznet commented
@amaltaro this PR is ready for review. One note though. The py3k lint checks fail with [round built-in referenced]() which is explained here https://stackoverflow.com/questions/59533912/what-is-the-alternative-to-built-in-round. I think we should not degrade about py2 compatibility and the [pylint documentation](https://pycodequ.al/docs/pylint-messages/w1633-round-builtin.html) suggests that it is only for backward compatibility, and therefore it should be ignored or it is better to adjust pylint configuration to skip this test.

2022-04-18 21:25 UTC, todor-ivanov approved these changes
Thanks @vkuznet 
The code looks good to me. 
And also thanks for fixing two of the old standing pylint warnings.

2022-04-19 00:04 UTC, amaltaro requested changes
This looks good to me, Valentin. However, given you are already on this, could you please update the same in this module:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/MicroService/Tools/PycurlRucio.py#L32-L38
?

Keep in mind there is an import that we can likely remove as well.

2022-04-19 11:00 UTC, vkuznet commented
Alan, I corrected `PycurlRucio.py` as well. Please review again.

2022-04-19 11:10 UTC, amaltaro approved these changes
Thanks Valentin, it looks good to me. Regarding pylint 3k, Erik and I had a brief chat and we also think it could be removed (AFAIR it checks whether our py2 code is compatible with py3, in some sense).

2022-04-19 11:10 UTC, merged