Given a block name in DBS3Upload config, dump its info as json
dmwm/WMCore pull request #11361
Opened 2022-11-11 09:50 UTC by amaltaro

Fixes #11358 

#### Status
ready

#### Description
Renamed the DBS3Upload `dumpBlock` attribute to `dumpBlockJsonFor`, such that now, whenever a block name string is provided for the component configuration, the component creates a json.dump of the same data that gets posted to the DBS server, through the client `insertBulkBlock` API.

#### Is it backward compatible (if not, which system it affects?)
NO (previous attribute is removed, a new one goes in)

#### Related PRs
None

#### External dependencies / deployment changes
None

2022-11-11 12:54 UTC, vkuznet requested changes
I suggest to expand this PR to support the following:
- the dumpBlockJsonFor should be a list to allow specify multiple block names
- we need to extract block ID and use it as a file name. Doing this way we'll preserve files for individual blocks and will not overwrite already existing file (as current behavior is doing). Moreover, the file name will allow to easily find block because block IDs are unique.

2022-11-11 13:52 UTC, amaltaro commented
@vkuznet That could be useful indeed, but I'd rather keep it as simple as possible. Otherwise we have to over-complicate a simple json dump to something like:
"""
get block hash id (split('#') etc)
is block hash id in list of block ids
  if so, does the hash id file exists; then don't overwrite it
  else dump json
"""

My experience shows that one block dump is usually enough to debug problems affecting multiple blocks.

BTW, the dump configuration is supposed to be used only to get a block dump, not to keep the component operating with that enable for any longer than that.

2022-11-11 16:16 UTC, vkuznet approved these changes
ok, it is your call, single block then.

2022-12-13 18:32 UTC, amaltaro commented
I am merging this but leaving the issue opened, as there are further discussions ongoing.

2022-12-13 18:32 UTC, merged