Add crt/key path resolution during service creation for RucioConMon.
dmwm/WMCore pull request #11398
Opened 2022-12-14 11:06 UTC by todor-ivanov

Fixes #11397 

#### Status
ready

#### Description
With the current change the path of the `cert/key` pair for the `RucioConMon` service object at `MSUnmerged`   is added to the object during creation time. This avoids consecutive path resolutions on every HTTP call during service's cache refresh. 

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

2022-12-15 08:51 UTC, amaltaro requested changes
Todor, given that you identified a general aspect to be improved, I would highly recommend to provide a general solution as well. So, instead of just resolving the RucioConMon instantiation here, can you please provide the relevant fix to the super class, likely here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Requests.py#L121-L123

and then, along the same Requests.py module, make sure that we don't waste CPU cycles trying to locate the cert/key files again, but simply check if it's already defined in the object, if it is, then go ahead and use it.

A bonus aspect here would be to actually rename the certificate key from `key` to `cert_key`, but we better change that at a later stage once unit tests are happy.

2022-12-15 14:44 UTC, todor-ivanov commented
Thanks @amaltaro  for your suggestion. 

I do agree for a more generic solution, but I have one clarification to make, about:
>  can you please provide the relevant fix to the super class, likely here:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Requests.py#L121-L123
>
> and then, along the same Requests.py module, make sure that we don't waste CPU cycles trying to locate the cert/key > files again, but simply check if it's already defined in the object, if it is, then go ahead and use it.

It kind of... the `Request` looks like a standalone class. It does not have a `super` /`sub`class relation with neither the `Service`  class nor with the higher level class (`RucioConMon` in this case). To me, it seems this is used as a direct instance as a class attribute in the `Service` class here:  https://github.com/dmwm/WMCore/blob/19c40202e5152faadbb32188ef9f91367eeefd73/src/python/WMCore/Services/Service.py#L150 
While the method inheritance happens between `RucioConMon` and `Service` class. So that's why I think it would be difficult from inside  the `Request` class to make a check if there is already a path defined in the wrapper object.  But let me see what I can think of.

2022-12-15 15:37 UTC, amaltaro commented
Your observation is correct, Todor. Just rephrasing my previous comment then:
* make the cert/key/capath look-up in the Service super class
* in the underlying Requests module, reuse those variables whenever it's set, otherwise keep calling the current methods (getCertKey).

2022-12-16 09:28 UTC, todor-ivanov commented
Hi @amaltaro 

Please take another look. 
One thing to mention in advance. I did not touch the Service Class at all, because looking at, it I noticed there is no concept of any kind of auth layer in it. It deals solely with managing caches, while the underlying `http(s)` parameters are just forwarded through the `config_dict` from the top level class to the `Requests` instance and left the later to deal with it. So rather than changing the concept here and adding  a bunch of lines of code in the Service class, I just suggested a `cert/key` path resolution to happen in the `Requests` class constructor. This achieves exactly the goals  you mention in your previous comment, but reduces the lines of new code.

2022-12-16 09:32 UTC, todor-ivanov commented
I need to admit - at the end, fixing the issue inside the `Requests` class turned out to be cheaper in terms of lines of code and is working perfectly well.

2022-12-16 11:10 UTC, amaltaro requested changes
It's looking much better now, thanks Todor. I left a couple of extra comments along the code though.

2022-12-16 19:06 UTC, amaltaro commented
test this please

2022-12-16 19:54 UTC, amaltaro approved these changes
It looks great, thanks Todor.

2022-12-16 19:54 UTC, merged