Add all the subpackages for each microservice
dmwm/WMCore pull request #11392
Opened 2022-12-12 18:55 UTC by amaltaro

Fixes #11391 

#### Status
not-tested

#### Description
Lack of subpackages has been tracked down to the setup_build.py script, which looks for the `+` sign in the package name to decide whether to recursively look for packages or not. I fixed only a couple of pylints on that one.

Real change has been made to the setup_dependencies module, where we list the required packages for each of the microservices.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None. However, a different way to fix it would be by enabling all the subpackages to be added by default. It might be less error prone in the future, but it would remove one level of freedom that we have right now...

#### External dependencies / deployment changes
New Pypi packages need to be rebuilt.

2022-12-12 21:49 UTC, vkuznet requested changes

2022-12-12 21:49 UTC, vkuznet commented on setup_build.py
> +        {'bin': ['bin_script_A'],
Honestly, I have no idea what `bin_script_A`, etc. means in this context. Therefore, at least I suggest to add proper doc string about to explain this notations.

2022-12-12 21:49 UTC, vkuznet commented on setup_dependencies.py
> +If a package ends with a '+', then all the subpackages are included as well.
Here, again, it is not obvious why and how `+` will enforce sub-package inclusion. Is it done by a specific step/script? If so, where does it comes from? I looked at content of the file and can't find any indication how plus sign is converted into set of action described in the line above. I suggest to provide proper documentation to explain how it is done and which script/function will take care of collecting and including sub-package info.

2022-12-13 05:24 UTC, amaltaro commented
@vkuznet I pushed in a second commit with a short documentation on this list of dependencies and how things are structured. Please have another look.

2022-12-13 12:30 UTC, vkuznet approved these changes

2022-12-13 16:37 UTC, amaltaro commented
Unstable unit test, merging it.

2022-12-13 16:37 UTC, merged