Add reqmgr2ms-pileup service
dmwm/WMCore pull request #11430
Opened 2023-01-09 16:34 UTC by vkuznet

Fixes #11423 

#### Status
in development

#### Description
First draft for MSPileup service

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
will add the following:
- Dockerfile
- FE rules

#### External dependencies / deployment changes

2023-01-09 21:13 UTC, vkuznet commented
@amaltaro , @todor-ivanov I made initial attempt to create MSPileup service. The changes are spread across multiple projects and I'll summarize them here:
- initial code base for MSPileup service, this PR
- changes to setup_dependencies.py, this PR
- changes to CI/CD, this PR
- [Dockerfile](https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/reqmgr2ms-pileup/Dockerfile)
- [frontend redirect rules](https://github.com/dmwm/deployment/pull/1229) in deployment repo
- reqmgr2ms-pileup configuration draft can be found in gitlab [services_configs/reqmgr2ms-pileup/config.py](https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/test/reqmgr2ms-pileup/config.py) repo
  - I used port 8249 as new port number for this service
- [reqmgr2ms-pileup.yaml](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/cmsweb/services/reqmgr2ms-pileup.yaml) k8s manifest file to deploy service to k8s cluster

I saw that pycurl_manager failed during unit tests which seems completely irrelevant here and rather an issue with access to cms-gwmsmon.cern.ch service, see [here](https://cmssdt.cern.ch/dmwm-jenkins/job/DMWM-WMCore-PR-test/13865/testReport/junit/WMCore_t.Services_t.pycurl_manager_t/PyCurlManager/testSingle/). I suggest that someone decide if we need to use this service in pycurl tests anymore but I doubt it has anything to do with this PR.

Said that, I need your initial review to proceed. If anything is missing or should be added feel free to point me to it. Meanwhile I tested new service in local setup and was able to get proper values from`/ms-pileup/status` and `/ms-pileup/info` end-points:
```
curl -v http://localhost:8249/ms-pileup/data/status
...
< HTTP/1.1 200 OK
...
{"result": [
 {
  "wmcore_version": "2.1.6rc5",
  "microservice_version": "2.1.6rc5",
  "microservice": "MSManager",
  "status": "OK"
}]}

curl -v http://localhost:8249/ms-pileup/data/info
...
< HTTP/1.1 200 OK
...
{"result": [
 {
  "wmcore_version": "2.1.6rc5",
  "microservice_version": "2.1.6rc5",
  "microservice": "MSManager",
  "request": null,
  "transferDoc": null
}]}
```

2023-01-12 16:07 UTC, amaltaro requested changes
@vkuznet all these changes are looking pretty good. I made a comment along the code that needs fixing.

In addition to that:
* on the Dockerfile, you have a typo in there `RUN pip install reqmgr2ms-pielup==$TAG`
* for the config.py, in services_config, I would suggest to start it with the bare minimum configuration at the moment and add attributes as we need them. I can get back to you with a candidate configuration soon.

Can you please also make sure that your comment in the middle of this PR gets incorporated to the very first comment in the PR?

2023-01-12 16:07 UTC, amaltaro commented on .github/workflows/pypi_build_and_images.yaml
> +                 reqmgr2ms-output reqmgr2ms-pileup, reqmgr2ms-rulecleaner, reqmgr2ms-transferor, reqmgr2ms-monitor]
Missing comma here.

2023-01-12 16:49 UTC, vkuznet commented on .github/workflows/pypi_build_and_images.yaml
> +                 reqmgr2ms-output reqmgr2ms-pileup, reqmgr2ms-rulecleaner, reqmgr2ms-transferor, reqmgr2ms-monitor]
done

2023-01-12 16:49 UTC, vkuznet commented
Alan, thanks for spotting missing comma and typo. I fixed both.

2023-01-12 16:56 UTC, vkuznet commented
Alan, I squashed the changes, updated PR description, and I think this PR is ready to go. Feel free to review again and merge. The confit file can be updated separately via gitlab PR and you may submit your version over there. Once this PR is merged I can continue on separate PRs for other (implementation) parts of new service.

2023-01-12 17:46 UTC, amaltaro approved these changes
It looks all good, thanks!

2023-01-12 17:52 UTC, amaltaro commented
PS.: I am removing this PR from the project because the project is supposed to be used only for GH issues. PR labels usually start with "PR:" as well, so I am removing those that are unneeded.

2023-01-12 17:55 UTC, merged