Change GH api to build release notes; plus refactoring
dmwm/WMCore pull request #11645
Opened 2023-07-05 20:20 UTC by amaltaro

Fixes #11640 

#### Status
not-tested

#### Description
Some overall refactoring of this script, it's worth highlighting though:
* changed GH API from search issues to commits pulls;
* less temp files.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

2023-07-06 10:03 UTC, todor-ivanov requested changes
@amaltaro There are few things I have noticed in this PR. Please take a look before merging. Other than that, it looks good and the results it produces are quite sensible  and seem to be solving the issue.

2023-07-06 10:21 UTC, amaltaro commented on bin/buildrelease.sh
>  done
The use case is: given a recent list of commit hash ids, fetch their equivalent pull request numbers. Building the release notes takes around a second, so I it's not clear to me what issue you are reporting here.

2023-07-06 10:27 UTC, todor-ivanov commented on bin/buildrelease.sh
> +git log --no-merges  --pretty=format:'%H %s (%an)' ${LASTCOMMIT}.. >> $TMP_HASHES_SUBJ_AUTHOR
Sorry Alan, my bad, I was not considering the fact that $LASTCOMMIT is actually the limiting commit freventing from going through the whole repository history. You may ignore my comment bellow as well.

2023-07-06 10:27 UTC, todor-ivanov commented on bin/buildrelease.sh
>  done
not a problem here... see my comment above

2023-07-06 10:54 UTC, amaltaro commented
@todor-ivanov I fixed one missing dollar sign that you noted - I think it was in the middle of your review - so you might want to have another look.
Nonetheless, before merging it, I will wait for further commits to get mergeed into the repository and run a final and clean real test before incorporating it.

2023-07-06 11:14 UTC, todor-ivanov approved these changes
thanks  @amaltaro  this looks perfect now

2023-07-07 16:07 UTC, amaltaro commented
Now that we have more commits at the HEAD, I could execute the final tests. I had to update 2 lines in the previous code:
1) the command with `sed` was not properly expanding the `$HASH_ID`. Resolved by replacing single quotes with double quotes.
2) not clear whether it really makes any difference, but when formatting git log to retrieve the author, I switched from `%an` to `%aN`. Which is what the script already uses.

Documentation on these log format can be found at: https://devhints.io/git-log-format

2023-07-07 18:34 UTC, amaltaro commented
This is working fine now. Merging

2023-07-07 18:34 UTC, merged