Update default rucio account for MSPileUp service
dmwm/WMCore pull request #11673
Opened 2023-07-25 15:01 UTC by khurtado

Fixes #11668

#### Status
on hold # to be tested with the new account once the rules are in place

#### Description
Change default rucio account for MSPileUp

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/reqmgr2ms-pileup-tasks/config.py
and
https://gitlab.cern.ch/cmsweb-k8s/services_config/-/blob/prod/reqmgr2ms-pileup/config.py

#### External dependencies / deployment changes
New rucio account x DN mapping needs to be in place

2023-07-25 15:04 UTC, khurtado commented
@amaltaro This change would complement the changes in from Valentin 
preprod: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/223
prod: https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/224

and what is still pending is the rucio account x DN mapping
Is this correct? 
After that, a new deployment and testing can be done.

2023-07-25 15:43 UTC, amaltaro commented
@khurtado that's correct. I feel like Eric worked on this account/identities yesterday, but it might be worth it pinging him today.

For the services_config, we are still missing the `test` pull request, as I see changes only for the `preprod` and `prod` branches.

2023-07-25 16:48 UTC, khurtado commented
@amaltaro Thanks! I will ping Eric via slack. Also, here is the test branch PR for reference (also in the GH issue comments):

https://gitlab.cern.ch/cmsweb-k8s/services_config/-/merge_requests/225

2023-07-25 17:33 UTC, amaltaro requested changes
@khurtado Kenyi, other than the test module that I left a comment in, everything seems to be fine for me. Can you please take that into consideration and make another review request please.

Please also link the 3 services_config PRs in the initial description of this PR (if not done yet). Thanks

2023-07-25 17:33 UTC, amaltaro commented on test/python/WMCore_t/WMSpec_t/Steps_t/Fetchers_t/PileupFetcher_t.py
> +        self.rucioAcct = "wmcore_pileup"
Kenyi, can you please remove this fix? It will go in in my PR fixing it on the workqueue layer.

2023-07-26 14:42 UTC, amaltaro approved these changes

2023-07-26 14:43 UTC, amaltaro commented
Thanks Kenyi! This will have to be backported to the `2.2.2_cmsweb` branch. I will do so together with https://github.com/dmwm/WMCore/pull/11670

2023-07-26 15:08 UTC, merged