Add campaign names support for stepchain workflows
dmwm/WMCore pull request #11738
Opened 2023-09-22 19:13 UTC by khurtado

Fixes #11705

#### Status
<n development

#### Description
Appends all campaigns available in a stepChain workflow job to the WMTask campaign name.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
<If it's a follow up work; or porting a fix from a different branch, please mention them here.>

#### External dependencies / deployment changes
<Does it require deployment changes? Does it rely on third-party libraries?>

2023-09-22 20:38 UTC, khurtado commented
Here are my test cases:

Structure:
workload Campaign = DMWM_Test
Step1 Campaign = CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step1
Step2 Campaign = CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step2
Step3 Campaign = CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step3

- Case 1:
[wmagent_SC_EL8_khurtado_sc8v13_noStep2Campaign_230922_201854_9245](https://cmsweb-test5.cern.ch/reqmgr2/fetch?rid=wmagent_SC_EL8_khurtado_sc8v13_noStep2Campaign_230922_201854_9245)

Workload campaign = yes
Step 1 campaign= yes
Step 2 campaign= no
Step 3 campaign= yes

Result:
campaignName = 'CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step1,DMWM_Test,CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step3'

- Case 2:
[wmagent_SC_EL8_khurtado_sc8v14_noStepCampaigns_230922_202131_1605](https://cmsweb-test5.cern.ch/reqmgr2/fetch?rid=wmagent_SC_EL8_khurtado_sc8v14_noStepCampaigns_230922_202131_1605)

Workload campaign = yes
Step 1 campaign= no
Step 2 campaign= no
Step 3 campaign= no

Result:
campaignName = 'DMWM_Test'

- Case 3:
[wmagent_SC_EL8_khurtado_sc8v17_noca_230922_202457_7564](https://cmsweb-test5.cern.ch/reqmgr2/fetch?rid=wmagent_SC_EL8_khurtado_sc8v17_noca_230922_202457_7564)

Workload campaign = no
Step 1 campaign= no
Step 2 campaign= no
Step 3 campaign= no

Result:
campaignName = 'DEFAULT_AcqEra'

- Case 4:
[wmagent_SC_EL8_khurtado_sc8v16_230922_202424_131](https://cmsweb-test5.cern.ch/reqmgr2/fetch?rid=wmagent_SC_EL8_khurtado_sc8v16_230922_202424_131)
Workload campaign = yes
Step 1 campaign= yes
Step 2 campaign= yes
Step 3 campaign= yes

Result:
campaignName = 'CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step1,CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step2,CMSSW_12_4_0_pre2__fullsim_noPU_2021_14TeV-1649399635Step3'

2023-09-22 22:30 UTC, khurtado commented
@amaltaro This is ready for review.

2023-09-23 01:19 UTC, amaltaro requested changes
@khurtado these changes are looking good to me.
Can you please cover this feature in a couple StepChain unit tests as well:
https://github.com/dmwm/WMCore/blob/master/test/python/WMCore_t/WMSpec_t/StdSpecs_t/StepChain_t.py
?

Side note, when creating a pull request (or issue), please update the fields/placeholders accordingly. The initial PR description needs to be revisited.

2023-09-23 01:19 UTC, amaltaro commented on src/python/WMCore/WMSpec/StdSpecs/StepChain.py
> +            uniqueCampaignNames = [x for x in campaignNames if not (x in seen or seen.add(x))]
It might be worth it adding a comment line saying that it is unique and it keeps the original content order.

2023-09-24 00:23 UTC, khurtado commented
@amaltaro Yes! I will add the unit tests

2023-09-25 11:43 UTC, khurtado commented
@amaltaro The unit tests have been added.

2023-09-25 12:21 UTC, amaltaro approved these changes
And now this feature is well covered. Thank you for providing those unit tests, Kenyi.

2023-09-25 12:21 UTC, merged