Refactor Unified configuration; remove unused references
dmwm/WMCore pull request #11770
Opened 2023-10-18 22:06 UTC by amaltaro

Fixes #11695 

#### Status
In development

#### Description
It turns out MSTransferor no longer depends on the Unified configuration, so this PR removes those unused references.

In addition, a script to inject the very basic Unified configuration is provided. It will be removed from this PR before it actually gets merged.

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

2023-10-18 22:09 UTC, amaltaro commented
And with the script provided in this PR, I have just updated/cleaned the Unified configuration in testbed, as can be seen in:
https://cmsweb-testbed.cern.ch/reqmgr2/data/unifiedconfig/config

2023-10-19 16:51 UTC, amaltaro commented
Oups, let me fix those unit tests before any code review.

2023-10-19 18:38 UTC, amaltaro commented
test this please

2023-10-19 23:56 UTC, amaltaro commented
And to not delay it any further, I have just updated the Unified configuration in central production to have the latest updates provided in the Unified repository.

2023-10-20 18:34 UTC, vkuznet requested changes

2023-10-20 18:34 UTC, vkuznet commented on bin/adhoc-scripts/injectUnified.py
> +    url = 'cmsweb-testbed.cern.ch'
please do not hard-code options, it is better if you'll use `sys.argv` to pass around it as an input option. If it is not provided then you can fall back to specific default (like this one)>

2023-10-20 18:34 UTC, vkuznet commented on bin/adhoc-scripts/injectUnified.py
> +                                       cert_file=os.getenv('X509_USER_PROXY'),
before making a call, please add block to check this env parameters, and if they are empty please provide meaningful message. The script should exit with non zero status in this case.

2023-10-20 18:34 UTC, vkuznet commented on bin/adhoc-scripts/injectUnified.py
> +            sys.exit(1)
if you exit here your connection will remain open, please refactor the code with `with` clause to automatically close the connection

2023-10-23 21:13 UTC, amaltaro commented
I actually planned to remove that script under "bin/adhoc-scripts/injectUnified.py", but it turns out we might actually need it for our testX kubernetes clusters, so I decided to keep it around and I have also applied the suggestions that you made, @vkuznet .

Initial description has been updated and it's now ready for another review. The unit test failure is unrelated - and actually unstable.

2023-10-24 11:14 UTC, vkuznet approved these changes

2023-10-24 13:44 UTC, merged

2024-01-15 13:12 UTC, amaltaro commented
I just noticed that the Unified configuration in testbed and production had all the previous parameters (in addition to the supported ones). After cross-checking the default configuration in WMCore against the P&R gitlab's one, I pushed the up-to-date data structure into testbed and production, from vocms0193 (latest agent):
```
python3 apps/wmagentpy3/bin/adhoc-scripts/injectUnified.py -c cmsweb.cern.ch
```