Logging typos fixed, maybe one error code definition too
dmwm/WMCore pull request #12054
Opened 2024-07-22 10:59 UTC by oljemark

Fixes #12051 

#### Status
not-tested 

#### Description
Fixes some logging output typos, that seem not have been hardcoded into parsing code elsewhere on github (except for the second commit with 'woud's ).
Is WMCore/Agent/Flow/DefaultFlow.py used at all? I only saw it in a help output from the flow generation as a default file to modify to your own needs, not run as is? If you want, I could cherry-pick the commits from https://github.com/dmwm/WMCore/compare/master...oljemark:WMCore:twiki-codes to this PR - the error code typo fix would also need simultaneous fix in the TWiki.

#### Is it backward compatible (if not, which system it affects?)
MAYBE 

#### Related PRs

#### External dependencies / deployment changes

2024-07-22 12:21 UTC, amaltaro commented
test this please

2024-07-22 20:12 UTC, amaltaro requested changes
These changes are looking good to me as well, but there is one module that needs to be updated (please see my comment along the code).

Once you make that change, could you please squash the new commit into the first one? In case you need some directions on that process, I find this https://steveklabnik.com/writing/how-to-squash-commits-in-a-github-pull-request a good source. Thank you again!

2024-07-22 20:12 UTC, amaltaro commented on src/python/WMComponent/JobCreator/JobCreatorPoller.py
> +                msg += "Passing over this error.  It will reoccur next interaction!\n"
This is actually supposed to be "iteration".

2024-07-22 21:51 UTC, oljemark commented
Hello. Fixed now, if you meant for the 2nd commit to remain separate.

2024-07-23 00:02 UTC, amaltaro commented
Great, thanks Fredrik!
Ideally, the 2nd commit would have only test/* changes, as mentioned in the contributing guidelines. But I appreciate your prompt fix and it is good to go!

2024-07-23 00:02 UTC, amaltaro approved these changes

2024-07-23 00:02 UTC, merged