update rucio client version
dmwm/WMCore pull request #12201
Opened 2024-12-10 14:51 UTC by vkuznet

Fixes #12032 

#### Status
not-tested

#### Description
New version for rucio-clients

#### Is it backward compatible (if not, which system it affects?)
MAYBE

#### Related PRs

#### External dependencies / deployment changes

2024-12-10 14:52 UTC, vkuznet commented
Alan, to proceed with testing we need to build new image which requires new tag. Therefore I made this PR to update version and asking for review. My understanding that we can merge this PR and then it will trigger new build images which can be used for deployment and testing.

Please advise how to proceed with that if procedure is different.

2024-12-10 15:10 UTC, amaltaro commented
@vkuznet I am pretty sure that, if we follow this path, it will require multiple follow up pull requests.

My suggestion is, first take this the requirements.txt file and install it in an empty virtual environment and/or in our dmwm-base docker image (well, a custom one):
https://github.com/dmwm/CMSKubernetes/blob/master/docker/pypi/dmwm-base/Dockerfile#L3

I think we will have to adapt other packages as well (add, remove, update version, etc). Once you have an apparently functional requirements.txt file, we can then go the full cycle (pypi packaging + docker build + execution of the application).

2024-12-16 18:51 UTC, amaltaro requested changes
Making this comment through a review, just so this PR does not show up whenever I look for PRs awaiting for human review.

2025-06-10 19:01 UTC, vkuznet commented
I used Dario's `2.4.0rc6` WM image (msoutput) and successfully installed new version of rucio clients via `pip install rucio-clients~=37.4.0`. Therefore, there is no conflicts in dependencies for version `37.4.0`. Next, we'll need to perform some rucio unit/integration tests to verify that this version works as expected. Here is list of its dependencies:
```
Name: rucio-clients
Version: 37.4.0
Summary: Rucio Client Lite Package
Home-page: https://rucio.cern.ch/
Author: Rucio
Author-email: rucio-dev@cern.ch
License: Apache License, Version 2.0
Location: /data/venv/lib/python3.12/site-packages
Requires: click, dogpile-cache, jsonschema, packaging, requests, rich, tabulate, typing_extensions, urllib3
```
But I also found that it is missing `rucio.db` package, e.g.
```
>>> import rucio.cli
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/venv/lib/python3.12/site-packages/rucio/cli/__init__.py", line 14, in <module>
    from rucio.cli import command  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.12/site-packages/rucio/cli/command.py", line 25, in <module>
    from rucio.cli.bin_legacy.rucio import ping, test_server, whoami_account
  File "/data/venv/lib/python3.12/site-packages/rucio/cli/bin_legacy/rucio.py", line 42, in <module>
    from rucio.cli.utils import exception_handler, get_client, setup_gfal2_logger, signal_handler
  File "/data/venv/lib/python3.12/site-packages/rucio/cli/utils.py", line 24, in <module>
    from rucio.client.client import Client
  File "/data/venv/lib/python3.12/site-packages/rucio/client/__init__.py", line 15, in <module>
    from .client import Client  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/venv/lib/python3.12/site-packages/rucio/client/client.py", line 32, in <module>
    from rucio.client.requestclient import RequestClient
  File "/data/venv/lib/python3.12/site-packages/rucio/client/requestclient.py", line 23, in <module>
    from rucio.db.sqla.constants import TransferLimitDirection
ModuleNotFoundError: No module named 'rucio.db'
>>> import rucio.db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'rucio.db'
```
Later, I found this module in `rucio` python package which should be installed separately from `rucio-clients`. Unfortunately, `rucio-clients` does not lists `rucio` as it dependencies, and therefore we must update our requirements.txt to install both.

2025-06-11 11:43 UTC, vkuznet commented
Here is associated issue https://github.com/rucio/rucio/issues/7746, and there is ongoing effort in https://github.com/rucio/rucio/pull/7747 to fix this issue in recent version of rucio clients.

2025-06-11 12:09 UTC, vkuznet commented
Based on DM MM discussion I was advised to downgrade rucio clients to recent stable release version `36.5.0`.

2025-06-11 13:14 UTC, mapellidario approved these changes
looks good to me

2025-06-12 15:53 UTC, anpicci approved these changes
Thanks @vkuznet, also for the interaction with the DM folks. That's fine with me as well.

2025-06-12 15:56 UTC, anpicci commented
I'm merging this PR, as we have reached the 2-approval quorum

2025-06-13 12:58 UTC, anpicci commented
Hi @vkuznet, could we check if the `--deep` flag reported in https://github.com/dmwm/WMCore/issues/12129 is deprecated with the version we are switching to? If yes, then I think we would need to remove the usage of `--deep` in our stack

2025-06-16 13:59 UTC, vkuznet commented
> Hi @vkuznet, could we check if the `--deep` flag reported in #12129 is deprecated with the version we are switching to? If yes, then I think we would need to remove the usage of `--deep` in our stack, i.e., [here](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/Rucio/Rucio.py#L221-L231)

Andrea, I checked with Rucio dev team and Hasan confirmed that the deep option is not yet deprecated and it is part of release for version `38`. The relevant issue for deep version is here https://github.com/rucio/rucio/issues/7118

2025-06-17 13:42 UTC, anpicci commented
Ok, so 36.5 should be safe, and we can live with it. Then I consider this PR concluded, thanks!

2025-06-18 10:06 UTC, merged

2025-07-09 16:07 UTC, amaltaro commented
After resolving a few issues with the CD pipeline, we finally reached an error that bounces back to this PR, see the build logs for `2.4.2rc3`: https://github.com/dmwm/WMCore/actions/runs/16174295315/job/45655464153#step:10:102

As Python packages have their own dependencies - and sometimes those are conflicting against each other - it is very important that whenever a third-party library is updated, that we go through the process of locally updating the requirements.txt file to ensure that versions are harmonized (either through a python venv, docker image, etc). @vkuznet

2025-07-09 17:05 UTC, vkuznet commented
The change to CMSMonitoring is provided here https://github.com/dmwm/CMSMonitoring/pull/299 it will align `jsonschema` version with one used by rucio clients package.