Better handling for step performance keys
dmwm/WMCore pull request #7257
Opened 2016-10-04 09:12 UTC by amaltaro

Complement #7242 and https://github.com/dmwm/WMCore/pull/7238

2016-10-04 13:14 UTC, amaltaro commented
test this please

2016-10-04 15:20 UTC, ticoann requested changes

2016-10-04 15:20 UTC, ticoann commented on src/python/WMCore/WMRuntime/DashboardInterface.py
> +        data['%d_ExeStart' % self.stepCount] = helper.name()
Why did we need the same value for different key? I just realized, should we need to add time faction instead of helper.name()?

2016-10-04 15:20 UTC, ticoann commented
test this please

2016-10-04 16:38 UTC, amaltaro commented on src/python/WMCore/WMRuntime/DashboardInterface.py
> +        data['%d_ExeStart' % self.stepCount] = helper.name()
Looked like a bug for me, indeed. However, looking at the documentation/twiki page:
https://twiki.cern.ch/twiki/bin/viewauth/CMS/InstrumentationOfWMAgentForDashboardReporting

it seems this is the correct input they expect..

2016-10-04 16:46 UTC, ticoann commented on src/python/WMCore/WMRuntime/DashboardInterface.py
> +        data['%d_ExeStart' % self.stepCount] = helper.name()
You are right. Although it is weird that we need two different key, I guess this is what was expected. Thanks for checking into

2016-10-04 16:46 UTC, ticoann approved these changes

2016-10-05 08:02 UTC, amaltaro commented
I'm just updating this error message to warning instead:
`logging.error('Failed to retrieve step cpu performance. Defaulting to 0')`

since performance info doesn't seem to be available for stageOut and logArch steps.

2016-10-05 19:47 UTC, amaltaro commented
@ticoann this one is also good to be merged

2016-10-06 03:37 UTC, merged