Hadle json.dumps failures in human readable form
dmwm/WMCore pull request #7479
Opened 2016-12-15 19:43 UTC by vkuznet

2016-12-15 19:45 UTC, vkuznet commented
Please take this PR instead of #7453

2016-12-15 20:42 UTC, ericvaandering requested changes
Please at least fix the things in bold here:
https://cmssdt.cern.ch/jenkins/view/All/job/DMWM-WMCore-PR-test/3682/artifact/artifacts/PullRequestReport.html#pylint

2016-12-15 20:51 UTC, vkuznet commented
Eric,
I don't remember if we agreed to follow pylint suggestions to fix lines which
didn't related to PR changes. In this case pylint complains about lines which
I never touched in my PR and in my opinion it should be done in separate PR,
since changes will not reflect PR purpose.

Please clarify. I'll be happy to make a separate PR for pylint suggestions,
but it really defeats the purpose of PR itself.

On  0, Eric Vaandering <notifications@github.com> wrote:
> ericvaandering requested changes on this pull request.
> 
> Please at least fix the things in bold here:
> https://cmssdt.cern.ch/jenkins/view/All/job/DMWM-WMCore-PR-test/3682/artifact/artifacts/PullRequestReport.html#pylint
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/7479#pullrequestreview-13216512

2016-12-15 20:54 UTC, vkuznet commented
Plus some suggested (in bold) changes are tricky to classify and their
resolution may require major code re-factoring. Here is clear example,
from pylint bold suggestion:
W0602, line 425 in stream_compress: Using global for '_stream_compressor' but no assignment is done

Not only global is bad by design, but assignment should be done. I have no idea
to which variable.


On  0, Eric Vaandering <notifications@github.com> wrote:
> ericvaandering requested changes on this pull request.
> 
> Please at least fix the things in bold here:
> https://cmssdt.cern.ch/jenkins/view/All/job/DMWM-WMCore-PR-test/3682/artifact/artifacts/PullRequestReport.html#pylint
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/7479#pullrequestreview-13216512

2016-12-15 21:00 UTC, ericvaandering commented
Please fix them, but what we generally do is add a *2nd commit* to this PR to address those changes. That makes review easy. If you are unsure (in general) if the purpose of the PR may need changes and new commits, you can wait.  But before it's merged, we should fix at least the most egregious errors.

Major changes should be avoided, I agree. Usually those are not the case.

2016-12-15 21:03 UTC, ticoann commented
I don't know why global variable is used.

> W0602, line 425 in stream_compress: Using global for '_stream_compressor' but no assignment is done

assignment is done in 

https://github.com/vkuznet/WMCore/blob/785179ae4be0d175de5fddda2763b51f7b9aa3c5/src/python/WMCore/REST/Format.py#L411

One other thing is something like following is legit case if we inherit the class and doesn't need to overwrite __init__ method

W0232, line 312 in RawFormat: Class has no __init__ method

2016-12-15 21:08 UTC, ericvaandering commented
Description

Used when a class has no __init__ method, and neither does its parent classes.


Are you sure the parent class has one?

2016-12-15 21:10 UTC, ericvaandering commented
RestFormat has no init(). Adding one will clear up all the errors. Maybe even converting it to RESTFormat(object) will do it.

2016-12-15 21:11 UTC, ticoann commented
> Used when a class has no init method, and neither does its parent classes.
> 
> Are you sure the parent class has one?

You are right parents class doesn't have __init__ method. In this case 
https://github.com/vkuznet/WMCore/blob/785179ae4be0d175de5fddda2763b51f7b9aa3c5/src/python/WMCore/REST/Format.py#L37

So we can add following in parent class.
```
def __init__(self):
    pass
```
But is this the right thing to do? If we don't have anything to initialize?

2016-12-15 21:12 UTC, ticoann commented
> RESTFormat(object) will do it.

I think that is better

2016-12-15 21:15 UTC, vkuznet commented
While, you're writing emails, I done all the changes.

2016-12-15 21:17 UTC, ericvaandering commented
I'm sure pylint will show this, but:

```
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
>>> dir(object)
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

so init is there to be picked up, I hope.

2016-12-15 21:18 UTC, ericvaandering commented on src/python/WMCore/REST/Format.py
> +    def __init__(self):
Like we said in our emails, I think inheriting from object will fix this with no other changes

2016-12-15 21:18 UTC, ticoann commented
You are too fast. :-) Sorry Valentin, could update with new class definition with object. I think that is cleaner

2016-12-15 21:22 UTC, vkuznet commented
I bet you'll ask for squash, what a saga :)

On  0, ticoann <notifications@github.com> wrote:
> You are too fast. :-) Sorry Valentin, could update with new class definition with object. I think that is cleaner
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/7479#issuecomment-267446786

2016-12-15 21:26 UTC, ericvaandering commented
Of the last two, probably. :-) But let Jenkins finish with it first if you don't mind. Having three running tests on the same bit of code may be confusing.

2016-12-15 21:28 UTC, ericvaandering approved these changes

2016-12-15 22:46 UTC, ericvaandering commented
Only thing holding up pylint is the global, which we agree is beyond the scope of this PR

2016-12-16 03:36 UTC, ticoann commented
And squashing the last 2 pylint related commit together. :-)

2016-12-16 13:46 UTC, vkuznet commented
Done

On  0, ticoann <notifications@github.com> wrote:
> And squashing the last 2 pylint related commit together. :-)
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/7479#issuecomment-267509648

2016-12-16 16:16 UTC, merged