add DAO to check DBS PhEDEx status
dmwm/WMCore pull request #7490
Opened 2016-12-21 17:43 UTC by ticoann

initial patch for getting DBS PhEDEx upload status from wmbs data.

still need to add 
1. AgentDataCollector need to add this info to wmstats report.
2. reqmgr2/or wmstats collect information and advance the status (will do this in the separate patch)
3. need to add unittest

2017-01-25 15:00 UTC, amaltaro requested changes
I still fail to see how we are going to use this information, though. It's good to know that the agent has already injected all the data into DBS/PhEDEx, but I'm almost sure Ops would still fire calls to DBS/PhEDEx to run other checks.

Do we actually use any of this combined information at the moment?

2017-01-25 15:00 UTC, amaltaro commented on src/python/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py
> +            completedWfs = self.dbsBufferUtil.getPhEDxDBSStatuForCompletedWorkflows(summary=True)
wrong method name

2017-01-25 15:00 UTC, amaltaro commented on bin/check-phedex-dbs-status
> +    result = dbsUtil.getPhEDxDBSStatuForCompletedWorkflows(summary=True)
wrong method name

2017-01-25 15:00 UTC, amaltaro commented on src/python/WMComponent/DBS3Buffer/MySQL/CheckStatusForCompletedWorkflows.py
> +            if info['status'] == "InDBS":
GLOBAL seems to be another popular state. This is something I want to investigate first to see whether we really need these 3 DBS status and what exactly is their meaning.

2017-02-20 22:21 UTC, ericvaandering commented on src/python/WMComponent/AnalyticsDataCollector/AnalyticsPoller.py
> +                                   Complted workflows(%s)..."""
Misspelled

2017-04-05 03:27 UTC, ticoann commented
replaced by #7757

2017-04-05 03:27 UTC, closed without merging