Add thread to check drain status
dmwm/WMCore pull request #7615
Opened 2017-02-10 22:12 UTC by goughes

Adding the skeleton thread for checking the drain status.  Need to figure out what database connections are needed and what drain info to write where.

2017-04-04 18:32 UTC, amaltaro commented
@goughes can you rebase it please? I'll review and run some tests tomorrow

2017-04-04 20:58 UTC, goughes commented
Well I don't think I did that right... I'll fix it.

2017-04-05 13:59 UTC, goughes commented
@amaltaro Take a look and let me know if that's what you wanted.

2017-04-05 14:23 UTC, ticoann commented
Hi Erik, there is still conflict on the current master. You would need to merge with master and rebase.

2017-04-05 16:42 UTC, ticoann commented
test this please

2017-04-05 17:28 UTC, amaltaro requested changes
Since we'll have to merge this drainInfo with all the information collected by AgentStatusWatcher, we'll have to somehow expose it to other classes.

Thinking on the best - and most pythonic - way of accomplishing it, how about we define a class variable and we access it via a classmethod (getter)? @ticoann @goughes any better idea?

2017-04-25 16:11 UTC, amaltaro reviewed
Changes look good now, Erik. Can you please fix those unit tests that are failing (I couldn't see a relationship with these changes, but...)?
Once that's fixed, we can test it in the agent itself.

2017-05-16 14:31 UTC, goughes commented
test this please

2017-05-18 15:29 UTC, goughes commented
The unittests that Jenkins says are failing work on my local machine using Docker.  Can someone give this a final review?  Let me know how important fixing the Pylint and Python3 tests are.

2017-05-18 15:51 UTC, amaltaro commented
test this please

2017-05-23 13:14 UTC, amaltaro commented
test this please

2017-05-23 19:16 UTC, amaltaro commented
@goughes the pylint unused imports warnings have to be fixed. Also fix the string format message please (instead of % it's comma). Others are not really fixable or take too much effort (like methods signature and arguments not used there).

The python3 import suggestions are supposed to be added to any new files.

However, the most important is understand and fixing the unit tests. BTW, please make a separate commit for all these pylint/pep8/unittests/code reformat stuff, such that we don't bother reviewing that, but only the actual code.

2017-05-24 15:05 UTC, amaltaro commented
test this please

2017-05-25 06:31 UTC, amaltaro commented
test this please

2017-05-29 09:11 UTC, amaltaro commented on src/python/WMComponent/AgentStatusWatcher/DrainStatusPoller.py
> +                msg += "Trace back: \n%s" % traceback.format_exc()
this traceback line can be removed (and the import). the logging.exception line below will automatically print the traceback.

2017-05-29 09:15 UTC, amaltaro commented
test this please

2017-05-30 07:46 UTC, amaltaro commented
@goughes did you manage to run a couple of workflows with this code? If so, then I think we're ready to merge it (after a minor comment I made yesterday)

2017-06-01 16:04 UTC, goughes commented
test this please

2017-06-08 14:57 UTC, amaltaro commented
test this please

2017-06-12 13:20 UTC, amaltaro commented
test this please

2017-06-19 13:23 UTC, amaltaro commented
I haven't seen any issues with this patch. I think it's good to be merged.
We still have to backport it to 1.1.4 wmagent branch, but I guess that can wait until we're about to cut the production release.

2017-06-19 14:37 UTC, ticoann commented
@goughes, Erik, could you squash the commit? I will merge the patch. Thanks,

2017-06-20 06:50 UTC, amaltaro commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix #7615 - Add thread to check drain status + AgentStatusWatcher unittest](https://trello.com/c/FTcLfCmV/40-fix-7615-add-thread-to-check-drain-status-agentstatuswatcher-unittest)

2017-06-22 04:33 UTC, ticoann commented
test this please

2017-06-22 06:07 UTC, ticoann commented
test this please

2017-06-22 07:58 UTC, amaltaro commented
How come it constantly fails... I cannot find anything, but breaking all these unit tests is not going to be good

2017-06-22 07:58 UTC, amaltaro commented
test this please

2017-06-22 11:26 UTC, amaltaro commented
@goughes or @ticoann would you mind running all the unittests for following files (maybe run 3 times each):
```
test/python/WMComponent_t/JobAccountant_t $ nosetests JobAccountant_t.py 
test/python/WMComponent_t/RetryManager_t $ nosetests RetryManager_t.py 
```

JobAccountant fails 1 out of 15 tests consistently. RetryManager is 100% success. I ran it on my VM, but that one is using oracle backend, which might be yielding different results than mysql/jenkins. Though I think `'NoneType' object has no attribute 'engine'` would affect both.

2017-08-15 11:49 UTC, amaltaro commented
@goughes @ticoann I think I got lost with this PR.
Since the drain status thread has been merged already in another PR https://github.com/dmwm/WMCore/pull/7955

is there anything else that we want from this PR? Maybe Erik should close it and start a fresh new one?

2017-08-15 14:05 UTC, goughes commented
@amaltaro @ticoann Closing this one.  I'll start a fresh PR for an AgentStatusWatcher unit test that doesn't use the emulators.

2017-08-15 14:05 UTC, closed without merging