allow 0 event file for job estimation
dmwm/WMCore pull request #7618
Opened 2017-02-12 06:46 UTC by ticoann

replace #7612.  Instead allowing  Jobs == 0 in workqueue elements, set the job 1 when number of events are 0 due to the file has 0 event.
Since there is legit case it shouldn't allow Job == 0 (in MC case)
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WorkQueue/Policy/Start/MonteCarlo.py#L113

@amaltaro, Alan please review

2017-02-13 08:08 UTC, amaltaro requested changes
BTW, is it really replacing #7612? If it does, then we have to make sure there are no elements with Jobs=0 in the system when it goes into production.

2017-02-13 08:08 UTC, amaltaro commented on src/python/WMCore/WorkQueue/Policy/Start/Block.py
> +                estimateJobs = ceil(float(block[self.args['SliceType']]) / float(self.args['SliceSize'])),
I'd suggest to just use this formula above in a `max(1, formula)`. For clarity, a line of comment saying that there may be 0 event files.

2017-02-13 17:57 UTC, ticoann commented on src/python/WMCore/WorkQueue/Policy/Start/Block.py
> +                estimateJobs = ceil(float(block[self.args['SliceType']]) / float(self.args['SliceSize'])),
Do you mean replace whole thing with max or just NumberOfEvents case.
I think only legit case for the formula to be 0 is when NumberOfEvents is 0. If other value (.i.e NumberOfFiles or NumberOfLumis), make this formula 0 there is some thing wrong with it, isn't it?

2017-02-13 18:39 UTC, ericvaandering commented on src/python/WMCore/WorkQueue/Policy/Start/Block.py
> +                estimateJobs = ceil(float(block[self.args['SliceType']]) / float(self.args['SliceSize'])),
Are these args already integers or are you converting from string? A quick search shows that you could get rid of all kinds of casting to floats simply by importing division from the future.

2017-02-13 18:51 UTC, amaltaro commented on src/python/WMCore/WorkQueue/Policy/Start/Block.py
> +                estimateJobs = ceil(float(block[self.args['SliceType']]) / float(self.args['SliceSize'])),
I'd replace the whole thing. NumberOfFiles=0 is already taken care and the block is rejected if that happens.
For NumberOfLumis - Eric can correct me - but I don't think we can have a EDM file without a lumi section.

2017-02-13 18:57 UTC, ericvaandering commented on src/python/WMCore/WorkQueue/Policy/Start/Block.py
> +                estimateJobs = ceil(float(block[self.args['SliceType']]) / float(self.args['SliceSize'])),
I think you are right

2017-02-13 19:29 UTC, ticoann commented
Alan, Eric, I updated the patch as you suggested. (I don't think string value is passed, I changed to  __future__ division)

2017-02-13 19:32 UTC, ericvaandering commented
Would you mind quickly updating lines 135 and 183 as well?

2017-02-13 19:48 UTC, ticoann commented
Thanks Eric, I didn't check other places. Patch is updated.

2017-02-13 21:11 UTC, ticoann commented
test this please

2017-02-14 04:05 UTC, ticoann commented
test this please

2017-02-14 06:50 UTC, amaltaro commented
test this please

2017-02-14 08:09 UTC, amaltaro commented
test this please

2017-02-14 17:01 UTC, ticoann commented
There are 3 failing unittests.

WMCore_t.Agent_t.HarnessCouchBackend_t.HarnessCouchBackend_t:testAddWorker changed from success to failure
WMCore_t.Services_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testCompletedWorkflow changed from success to failure
WMCore_t.Services_t.WorkQueue_t.WorkQueue_t.WorkQueueTest:testWorkQueueService changed from success to failure

First one seems to be temporary error. The other 2 is due to the changes (previous Jobs count was 0 but new patch change those to 1) - updated the patch now. Hopefully it will pass the unittest now.

2017-02-15 12:43 UTC, amaltaro approved these changes

2017-02-15 15:41 UTC, merged