Accept either string or list of strings for ScramArch at spec level
dmwm/WMCore pull request #7623
Opened 2017-02-15 13:40 UTC by amaltaro

Fixes #7578
We then validate and convert the user input into a python list of strings (even if user provided only a basic string), otherwise it's a bit more complicated to do the data sanitisation.

Still to be tested.

2017-02-15 14:13 UTC, ericvaandering commented
Looks like this is blowing up in Jenkins...

2017-02-15 14:14 UTC, ericvaandering commented
WMCore_t.WMSpec_t.StdSpecs_t.MonteCarloFromGEN_t.MonteCarloFromGENTest.testMonteCarloFromGEN says scramArch is None

2017-02-15 14:18 UTC, amaltaro commented
Com'on!! It's supposed to be a simple change :(

2017-02-15 17:47 UTC, amaltaro commented
test this please

2017-02-15 19:14 UTC, ericvaandering commented
Almost there. :-)

2017-02-15 19:40 UTC, amaltaro commented
And it should get fixed with my last commit. I like it, it means we have a quite reasonable unit test coverage now (though there is a lot to improve, of course) :-)

2017-02-16 13:39 UTC, amaltaro commented
Most of the StdBase pylint warnings were fixed in 7619. In terms of spec level, it works as expected. I also took a change to look at a couple of condor jdl and a job runtime and everything looks fine (though we have to check it again in the near future).

From my side it's good to go.

2017-02-16 14:47 UTC, ericvaandering requested changes

2017-02-16 14:47 UTC, ericvaandering commented on src/python/WMCore/WMSpec/WMWorkloadTools.py
> +def makeNonEmptyList(stringList):
I'd rather see this in Utils (perhaps true of everything here) with a generic exception. But I think there is already exactly this in WMObject if you are inheriting from that. 

Having this general purpose stuff scattered around is a PITA.

2017-02-16 14:47 UTC, ericvaandering commented on test/python/WMCore_t/WMSpec_t/StdSpecs_t/StepChain_t.py
> +        self.assertItemsEqual(task.getScramArch(), ['slc6_amd64_gcc481'])
Nicely done. :-)

2017-02-16 14:47 UTC, ericvaandering commented on test/python/WMCore_t/WMSpec_t/WMWorkloadTools_t.py
> +
Since it has the same behavior, you should test that's true with a few of your other examples. Test make list against make non empty

2017-02-16 15:31 UTC, amaltaro commented on src/python/WMCore/WMSpec/WMWorkloadTools.py
> +def makeNonEmptyList(stringList):
Hmm, I'm not sure we can define (cast) the spec input parameters to a WMObject (if you have an idea, I'm all ears). Perhaps what we could do is to add these functions as WMObject methods and create some sort of wrapper functions in Utils (but then we have the Utils dependency on WMCore/DataStructs).

Or I could simply move these functions to Utils/Utilities or something like that.

2017-02-16 15:31 UTC, amaltaro commented on test/python/WMCore_t/WMSpec_t/WMWorkloadTools_t.py
> +
will do

2017-02-16 15:46 UTC, ericvaandering commented on src/python/WMCore/WMSpec/WMWorkloadTools.py
> +def makeNonEmptyList(stringList):
Definitely no dependencies from Utils onto something else. The idea with Utils is that *any* python project might benefit just by grabbing it.

What would it take to just move both make*List functions to Utils?

2017-02-16 16:37 UTC, ticoann commented
test this please

2017-02-16 16:45 UTC, amaltaro commented
Eric, I changed the unit tests as you suggested. Can you check and approve it if it's Ok?
As we discussed in the meeting, I'll work on this issue https://github.com/dmwm/WMCore/issues/7633 once this one gets merged.

2017-02-16 16:46 UTC, ericvaandering approved these changes

2017-02-16 17:46 UTC, amaltaro commented
To be on the safe side, triggering jenkins once again.

2017-02-16 17:46 UTC, amaltaro commented
test this please

2017-02-16 18:34 UTC, amaltaro commented
@ticoann I think we can merge it now

2017-02-16 20:22 UTC, ticoann approved these changes

2017-02-16 20:22 UTC, merged