Remove duplicate logic.
dmwm/WMCore pull request #7726
Opened 2017-03-15 18:27 UTC by bbockelm

Except for `REQUIRED_OS`, the same Requirements logic is currently in both HTCondor `startd`s and WMAgent.  Remove the logic from the agent so we can make changes from a single place.

For `REQUIRED_OS`, we keep the logic but:
- Left a TODO to remove it once `T2_CH_CERN_HLT` has made the corresponding
  change.
- Add support for `GLIDEIN_REQUIRED_OS="any"` (for pilots that use singularity).

@ericvaandering @hufnagel @amaltaro - please note, as you've been doing `REQUIRED_OS` work recently.

2017-03-15 18:33 UTC, bbockelm commented
To work with existing pilots, would it be possible to add the following to the WMAgents:

```
config.BossAir.condorRequirementsString = '(REQUIRED_OS=?="any") || (GLIDEIN_REQUIRED_OS=?="any") || stringListMember(GLIDEIN_REQUIRED_OS, REQUIRED_OS)'
```

2017-03-17 13:33 UTC, amaltaro requested changes
I'm not sure I understood your comment. 
HTCondor (or is it glideinWMS?) already has a *default* requirement string expression. 

By setting it from the agent side, don't we have the capability to overwrite that and enforce this one to be evaluated during job matchmaking? 

If we remove it from the agent, then we no longer can say how the the production jobs are supposed to match to resources and what's taken into account (I mean, we are blindly trusting that SI will always have the correct  expr).

2017-03-17 13:33 UTC, amaltaro commented on src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py
> +        self.reqStr = ('((REQUIRED_OS=?="any") || '
Isn't it going to match against any sites? Since you removed the "DESIRED_Sites" logic from the requirements string.

2017-03-17 13:33 UTC, amaltaro commented on src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py
> +        # Build a request string.  All CMS resources match DESIRED_Sites on the START
This plugin may soon be gone, so maybe put these comments on the other plugin instead.

2017-03-17 13:39 UTC, bbockelm commented
The same site / OS matching logic is on both the worker node and in the WMAgent jobs.

Since both filters must pass, having the logic duplicated in two places makes deploying changes much, much longer and require more effort.

For example, the recent changes WMAgent has been trying with `REQUIRE_OS` require a new agent version and a corresponding change on the SI side.  If you didn't put it by default in the code, then it would only require a change on the SI side.

Put another way - has there ever been a case where the WMAgent defaults need to be more restrictive than the HTCondor defaults?

2017-03-17 19:15 UTC, ticoann commented
test this please

2017-03-20 19:25 UTC, amaltaro commented on src/python/WMCore/BossAir/Plugins/PyCondorPlugin.py
> +        # Build a request string.  All CMS resources match DESIRED_Sites on the START
@bbockelm "All CMS resources match DESIRED_Sites on the START expression side". Where is the START expression evaluated? Where is the second expression evaluated?

If any site is eligible to run jobs, then why not just remove this part of the expression and leave only the REQUIRED_OS + GLIDEIN_REQUIRED_OS validation?

2017-03-20 19:26 UTC, amaltaro commented
BTW, if we are not desperate to have this change in the global pool, I suggest we put it in only for the next agent release.

2017-03-29 02:14 UTC, bbockelm commented
@amaltaro - I think the only possible urgent need of this is if we need to do a lot of RHEL7 work before the next agent validation.  Jean-Roch asked about this earlier today and I will point him at this ticket for reference.

2017-03-29 06:12 UTC, amaltaro commented
@bbockelm one more question, once we remove the `Requirements` expression from these plugins, where and how can we find it?

2017-03-29 08:35 UTC, amaltaro commented
I asked these questions to James and Diego D. and I think it's more clear now.
Just in case, I'm running a few workflows in ITB before we push it to the production agents.

2017-03-29 13:58 UTC, amaltaro commented
@bbockelm can you squash these commits please? Thanks

2017-03-31 09:20 UTC, amaltaro approved these changes

2017-03-31 09:26 UTC, amaltaro commented
@ticoann please merge

2017-04-04 18:27 UTC, merged