add the DAO to check incomplete workflow in agent
dmwm/WMCore pull request #7775
Opened 2017-04-06 03:50 UTC by ticoann

For checking draining status, use this for the first check if this passes check the DBS, PhEDEx upload status.

2017-04-12 15:34 UTC, amaltaro requested changes
A few minor issues need to be addressed, otherwise the code looks good.

However, I think we should make this DAO a bit more generic to avoid creating gazillions of DAOs for the draining process. I thought we could make it return two different results:
1) just a boolean flag, as it is already implemented
2) return distinct names - for cases we want to know further what are the workflows still holding us on this draining.

So we could replace that SQL query by
`select distinct name from dbsbuffer_workflow WHERE completed=0;`
what do you think?

2017-04-12 15:34 UTC, amaltaro commented on src/python/WMComponent/DBS3Buffer/DBSBufferUtil.py
> +        completeFWFlag = self.daoFactory(classname="isAllWorkflowsCompleted")
dao name is wrong

2017-04-12 15:34 UTC, amaltaro commented on src/python/WMComponent/DBS3Buffer/Oracle/IsAllWorkflowsCompleted.py
> +
no need for all these blank lines :)

2017-04-12 15:34 UTC, amaltaro commented on src/python/WMComponent/DBS3Buffer/Oracle/IsAllWorkflowsCompleted.py
> +    Oracle version
you probably forgot to close this docstring and pass this class

2017-04-26 12:35 UTC, ericvaandering commented
test this please

2017-06-14 14:22 UTC, ticoann commented
included in #7926

2017-06-14 14:22 UTC, closed without merging