get draining parameter from aux db
dmwm/WMCore pull request #8011
Opened 2017-07-18 18:47 UTC by ticoann

replace #7731 #7923

2017-07-18 21:05 UTC, ticoann commented
@amaltaro, Alan please review.

2017-07-21 14:07 UTC, ticoann commented
test this please

2017-07-24 16:06 UTC, amaltaro requested changes
A few minor things to fix and possible some other minor improvements. Until those are fixed, you have my red flag :-)
And sorry for taking so long to review it!

2017-07-24 16:06 UTC, amaltaro commented on src/python/WMCore/Services/ReqMgrAux/ReqMgrAux.py
> +    def isWMAgentDraining(self, agentName, agentDrainCondition=None):
Now that I finished reading this module. I think we should separate getters from setters. And this method is clearly a getter (by its name), but it also uploades the couch record.

Just an idea, whatever is calling `isDrainMode` should first call a `updateDrainMode` or something like that and only then call `isDrainMode`. 
Second option would be renaming this method to `updateDrainMode` and moving the final logic to `isDrainMode`.
Third option is something better that you'll probably suggest :)

2017-07-24 18:58 UTC, ticoann commented on bin/deploy-wmagent.sh
> +echo "Done!" && echo
Yes, you're right. I will do that.

2017-07-25 18:33 UTC, ticoann commented
test this please

2017-07-26 18:16 UTC, ticoann commented
test this please

2017-08-07 15:24 UTC, ticoann commented on src/python/WMCore/ReqMgr/Service/Auxiliary.py
> +    def put(self, subName=None):
Hmm, I didn't see previous reply for this. (I am pretty sure I did).  
The problem is there is "_"  prefix from subName so even if we have empty sting as default we still need a if else statement.

2017-08-07 15:27 UTC, ticoann commented on src/python/WMCore/ReqMgr/Service/Auxiliary.py
> +            if propertyDict:
Every property values is required explicitly. So if agent is out of drain, it should have explicitly say {"AgentDrainMode": False} and current code (with this patch) will do that.

2017-08-08 19:17 UTC, merged