'division' fix applied
dmwm/WMCore pull request #8125
Opened 2017-09-05 11:41 UTC by vilnius-dev

"from __future__ import division" added in each file that contains division

2017-09-05 16:30 UTC, ericvaandering commented
This looks like the 2to3 fixer, not the old_div fixer from futurize was applied. 

But like I said, I think this division issue requires some actual thinking. Figuring out which version is most appropriate for each piece of code. I don't want to be stuck, 5 years from now, with a bunch of unnecessary dependencies on futurize's old_div

2017-09-20 09:38 UTC, amaltaro requested changes
Roman, I made several comments along this PR. Please update it.
I didn't check the test/* files since they should all be fine, otherwise unit tests would fail.

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMComponent/AgentStatusWatcher/ResourceControlUpdater.py
All divisions in this module are integer, so L223-224, L234-236, L259-264 (//)

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMComponent/JobArchiver/JobArchiverPoller.py
>  __all__ = []
Integer division in L248 (and int can be removed)

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMComponent/JobCreator/CreateWorkArea.py
>  import os
Integer division in L315

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMComponent/JobCreator/JobCreatorPoller.py
>  __all__ = []
Integer division in L116

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMComponent/PhEDExInjector/PhEDExInjectorPoller.py
Integer division in L90 (int and round can be removed)

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMComponent/TaskArchiver/CleanCouchPoller.py
>  import json
Integer division in L720 and 726

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMCore/Algorithms/MathAlgos.py
Remove float from L61, L131, L188,

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMCore/BossAir/Plugins/MockPlugin.py
Integer division L225

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMCore/Credential/Proxy.py
Integer division in L213 (and remove int)

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMCore/DataStructs/MathStructs/ContinuousSummaryHistogram.py
>  import math
Remove float from L164

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMCore/Database/CMSCouch.py
Integer division L1148

2017-09-20 09:38 UTC, amaltaro commented on src/python/WMCore/JobSplitting/EventAwareLumiBased.py
Remove float L123, L172, L183, L274
Remove math.floor and float L183

2018-08-28 20:52 UTC, ticoann commented
I think this division change has to have more testing and code review. We will go file by file approach with this.

2018-08-28 20:52 UTC, closed without merging