check the PATH for condor_chirp command
dmwm/WMCore pull request #8536
Opened 2018-03-28 04:19 UTC by ticoann

@hufnagel, Dirk, is this what you were thinking to get the right path in Singularity container?
I am not sure whether PATH would be set correctly in Singularity. We can find all the path as well but that would take long time (might be better to look for certain paths if we knows some candidate)

2018-03-28 04:24 UTC, ticoann commented on src/python/WMCore/WMSpec/Steps/Executor.py
> +
This code doesn't check whether file is executable (assumes condor_chirp is executable).

2018-03-28 07:50 UTC, hufnagel requested changes

2018-03-28 07:50 UTC, hufnagel commented on src/python/WMCore/WMSpec/Steps/Executor.py
> +#TODO this function can me moved to Utils.
Yeah, that would have been my comment, a function like this really belongs into Utils.

2018-03-28 07:50 UTC, hufnagel commented on src/python/WMCore/WMSpec/Steps/Executor.py
> +        fullPath = path + os.sep + name
fullPath = os.path.join(path, name)

2018-03-28 07:50 UTC, hufnagel commented on src/python/WMCore/WMSpec/Steps/Executor.py
>          if condor_chirp_bin:
Per your other comment, maybe we should add

and os.access(condor_chirp_bin, os.X_OK)

2018-03-28 14:40 UTC, ticoann commented
@hufnagel, Dirk I updated the patch as you suggested. 
@amaltaro, Alan, could you review the patch as well

2018-03-28 15:15 UTC, amaltaro approved these changes
Patch looks good, Seangchan.
I'm just wondering whether we could make it slightly more generic, where one also provides the environment variable (e.g. PATH, PYTHONPATH, etc) as parameters to getFullPath.

2018-03-28 15:16 UTC, amaltaro commented on test/python/Utils_t/FileTools_t.py
>  if __name__ == "__main__":
we could have a couple of blank new lines above

2018-03-28 15:46 UTC, hufnagel approved these changes

2018-03-28 15:54 UTC, ticoann commented
Thanks Alan, I updated the patch as you suggested. I will run the test in my vm whether it breaks anything, and if it goes OK. I can patch  cmsgwms-submit6 hepcloud agent.

2018-03-28 18:21 UTC, amaltaro commented
Thanks, Seangchan. It looks good!

2018-03-29 02:31 UTC, hufnagel commented
Would check with Ops if this is wanted in all agents as well since it affects all sites that use singularity. I'll definitely add it to the Tier0 deployment instructions.

2018-03-29 04:11 UTC, ticoann commented
I create the branch patch (#8538) and updated hepcloud agent. (My vm test at least didn't break anything - I am not sure it will fix the problem though since PATH is not guaranteed to set correctly for condor_chirp) If the patch fixes the problem we can apply to that to all agent)

2018-03-29 06:48 UTC, bbockelm commented
Hi @ticoann -

CMSSW searches `$PATH` for Singularity and CMSSW-based jobs have been reporting without a problem.

Brian

2018-04-03 13:30 UTC, amaltaro commented
> CMSSW searches $PATH for Singularity and CMSSW-based jobs have been reporting without a problem.

well, what's the problem then (if any)? How can we check whether a job is properly reporting from inside CMSSW? I think we can run a workflow in a singularity-based site (Nebraska e.g.), fail all jobs, look up at Kibana and check the step exit code(?)

2018-04-03 20:34 UTC, hufnagel commented
It works. Jobs at PSC which have this problem chirp from within CMSSW just fine. With the patch they also chirp the exit codes from the WMCore runtime wrapper.

2018-04-04 02:29 UTC, ticoann commented
Thank you for checking, Dirk. I am merging this then.

2018-04-04 02:30 UTC, merged