add edmcopyutil fallback for older cmssw releases, fixes #8665
dmwm/WMCore pull request #8788
Opened 2018-09-05 03:15 UTC by hufnagel

Completely untested, but you get the idea.

2018-09-14 16:00 UTC, ticoann commented
@hufnagel, this only affects CMSSW version less than 8, right? We have some of the test workflows using CMSSW_7_X_X, I will run the test and merge this.

2018-09-14 16:15 UTC, hufnagel commented
Yes, correct, the new code path should not be active for any newer CMSSW releases.

2018-09-14 19:10 UTC, amaltaro commented
Hmm, I'm not sure it's a good idea to have the cmssw and scram hardcoded in all these LogCollect jobs.
Eventually it will get deprecated and removed from CVMFS, and when we notice it it will be too late and ALL sandboxes will have to be patched to a proper release.

2018-09-16 00:30 UTC, bbockelm commented
If CMSSW_8 is deprecated and removed, then we hopefully won’t have any sandboxes running CMSSW_7!

2018-09-17 06:00 UTC, amaltaro commented
How about we use one of the latest 10_x_y stable releases? This 8xy must be almost 2 years old now.
In addition to that, @hufnagel please add a log line such that we know when the LogCollect job had to use the hardcoded release.

2018-09-17 14:38 UTC, hufnagel commented
Why ? The edmCopyUtil is supported for CMSSW_8_X and the CMSSW_8_X series will stay around as long or longer than the CMSSW_7_X series. Is there any technical advantage to going to CMSSW_10_X ?

2018-09-18 10:37 UTC, amaltaro commented
Ok, I had a quick chat with David L. and, in short, it doesn't really matter since they don't manage to deprecate releases.
However, between picking 800 or a 10x, he would go with 10_2x. Looking at this list for production releases and their production arch:
https://cmssdt.cern.ch/SDT/cgi-bin/ReleasesXML

how about we use CMSSW_10_2_3 for slc6_amd64_gcc700 ? I see there is a 10_2_5, but it has a patch release, so either we pick that patch1, or we step back a bit and use 10_2_3.

Dirk, don't forget adding that log line. Thanks

2018-09-18 15:34 UTC, hufnagel commented
If we should use CMSSW_10_2_X for every CMSSW_7_X release or older, how about we use it for every CMSSW_10_2_X release or older ? I mean, if we override anyways and the newer is better, lets just override for anything older and take advantage of the new xrootd clients. Also makes it easier to test/validate the override code path.

2018-09-18 16:06 UTC, amaltaro commented
Hmm, I don't have a strong opinion on that. However, I'd not override it unless we must to.
Otherwise, in 10 years from now we might find this code trying to use 10_2 that is long gone :-)

2018-09-18 19:32 UTC, amaltaro commented
I don't really know what you want. I didn't suggest to change anything on your approach but using a newer CMSSW release. Honestly, we're over discussing something that should be much simpler.

2018-09-18 20:04 UTC, hufnagel commented
My point is that we use the original CMSSW release for anything CMSSW_8_X or newer. If we say that CMSSW_8_X is no good for overriding older CMSSW, why would it be good for CMSSW_8_X itself ? It's ok or it isn't. There is zero technical reason I've heard so far why CMSSW_10_2_X is better than CMSSW_8_X. If there were, I should override every other pre-CMSSW_10_2_X release as well.

Anyways, all of this doesn't matter one way or another. I am overriding with CMSSW_10_2_3 and adding the log line to be done with this.

2018-09-18 20:08 UTC, amaltaro commented
Technical reason 10_2 is better than 8_0 is the whole software package/clients that come with it. Newer xrootd client, newer gcc, newer openssl, and newer release. Why override old releases with a somehow new'ish release if you can have one even newer(?)

2018-09-18 20:09 UTC, hufnagel commented
Well then, so the logic should be:

if cmssw < 10_2_3:
  use 10_2_3
else:
  use cmssw

???

2018-09-18 20:17 UTC, amaltaro reviewed
Besides the minor log fix, changes look good. Thanks!

2018-09-18 20:17 UTC, amaltaro commented on src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
> +                    logging.warning("WARNING: CMSSW too old to support edmCopyUtil, using CMSSW_10_2_3 instead")
This `WARNING` in the message body can go away. Logging should take care and record the log level altogether.

2018-09-19 14:37 UTC, amaltaro commented
Hmm, according to the job logs, I don't actually see that code being executed... wait, I found a problem in this patch. Commenting in the code.

2018-09-19 14:41 UTC, amaltaro requested changes
Dirk, given that LogCollect always have a CMSSW release configured. Should we also rework that `useEdmCopyUtil` flag such that it will always evaluate to True? Thus, ALL logcollect jobs use the edmCopyUtils.

If not, then you just need to fix the scramArch thing mentioned in the code

2018-09-19 14:41 UTC, amaltaro commented on src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
> +                elif cmssw_major < 8 and scramArch.startswith('sl6_amd64_'):
`slc6_amd64_` instead of `sl6_amd64_`

2018-09-19 14:49 UTC, hufnagel commented
By removing the stagein support from LogCollect jobs, we would explicitly say  that we do not support any non-sl6 releases earlier than CMSSW_8_X. Which is a policy decison, although practically speaking I don't think there are such releases. @bbockelm , opinion ?

Once we have that decision, yes, we could clean up the code and remove the whole stagein code path.

2018-09-19 14:50 UTC, hufnagel commented
Not sure though if you want to do this in this ticket or open another one...

2018-09-19 14:50 UTC, hufnagel commented on src/python/WMCore/WMSpec/Steps/Executors/LogCollect.py
> +                elif cmssw_major < 8 and scramArch.startswith('sl6_amd64_'):
Working on it...

2018-09-24 15:30 UTC, amaltaro commented
It works
```
2018-09-21 10:51:20,121:WARNING:LogCollect:CMSSW too old to support edmCopyUtil, using CMSSW_10_2_3 instead
2018-09-21 10:51:20,121:INFO:LogCollect:Running scram
2018-09-21 10:51:24,585:INFO:LogCollect:Running edmCopyUtil
2018-09-21 10:51:24,591:INFO:Scram:    Invoking command: env X509_USER_PROXY=/srv/myproxy.pem edmCopyUtil /store/unmerged/...
```

@ticoann from my side this can go in.

2018-09-24 15:31 UTC, amaltaro approved these changes

2018-09-24 15:33 UTC, ticoann commented
Thanks, Alan, Dirk. I am merging this since this is only agent side change.

2018-09-24 15:46 UTC, merged