replace cherrypy.request.user
dmwm/WMCore pull request #8871
Opened 2018-10-25 17:35 UTC by ticoann

related to #8868

2018-10-25 17:36 UTC, ticoann commented
@amaltaro, Alan please review

2018-10-25 19:41 UTC, ticoann commented
test please

2018-10-25 21:01 UTC, ticoann commented
test this please

2018-10-25 22:06 UTC, amaltaro requested changes
I made a comment in the code that has to be updated. I guess that's why that unit test keeps failing

2018-10-25 22:06 UTC, amaltaro commented on src/python/WMCore/ReqMgr/Service/Request.py
> +        dn = get_user_info("dn", "unknown")
`dn = get_user_info().get("dn", "unknown")`

2018-10-25 23:33 UTC, ticoann commented
Thanks Alan, I updated the patch.

2018-10-26 02:40 UTC, ticoann commented
Error is very weird. I wonder why it didn't fail before. (hope second commit fix that problem)

2018-10-26 03:30 UTC, ticoann commented
Alan if this looks OK, please included in the new tag. If not we can push this later.

2018-10-26 09:15 UTC, amaltaro commented
Thanks!

2018-10-26 09:15 UTC, merged