StompAMQ changes to integrate with different versions
dmwm/WMCore pull request #8974
Opened 2019-01-21 15:05 UTC by stiegerb

- Renamed `make_notification` to `make_notification_list` without changes.
- Added new `make_notification` method that produces a single notification.
- Adding new functionality to pass user-defined metadata.
- No longer add unnecessary `'payload'` subfield to notification body.

We can discuss here how best to proceed. In my opinion, `make_notification_list` is still confusing, as it assigns the same document id, type, and timestamp to all notifications. As in this PR now, it's also not really consistent with the other method, as it still uses the `'payload'` subfield.

2019-01-21 15:44 UTC, vkuznet commented
I would suggest to keep payload for backward compatibility but make it as optional function argument (and be last argument). If provided then you can structure the body of the doc to have payload otherwise leave as is.

2019-01-21 16:13 UTC, leggerf commented
+1

2019-01-21 16:15 UTC, vkuznet commented
+1

2019-01-21 19:59 UTC, amaltaro requested changes
Patch looks good in general. I made a few comments in the code and in addition to that, how about we bump the module version to 0.3?
https://github.com/dmwm/WMCore/blob/af82fc85a83e5f1eaaaad472f089cf52779e0fb0/src/python/WMCore/Services/StompAMQ/StompAMQ.py#L69

Thanks for creating this PR, Benjamin.

2019-01-21 19:59 UTC, amaltaro commented on src/python/WMCore/Services/StompAMQ/StompAMQ.py
> +        :return: a list of notifications with the proper metadata
"a list with a single notification"

2019-01-21 19:59 UTC, amaltaro commented on src/python/WMCore/Services/StompAMQ/StompAMQ.py
> +        :param metadata: user metadata to be added. (Updates generic metadata.)
maybe say it's a dictionary with user metadata.

2019-01-21 19:59 UTC, amaltaro commented on src/python/WMCore/Services/StompAMQ/StompAMQ.py
> +                    'uuid': makeUUID()}
given that `id` is already meant to be unique, I wonder whether we actually have any need for `uuid`?

2019-01-21 20:04 UTC, vkuznet commented
One more comment. The code now contains both CamelLike and python_like naming convention. Can we converge of using underscore (python way) for all names/variables? For instance, a function `make_notification` takes `docType` and `payload_subfield`.

2019-01-21 20:34 UTC, amaltaro commented
Actually we adopted the camelCase convention in WMCore, but as you pointed out, there is a large fraction of the code using both convention...
https://github.com/dmwm/WMCore/blob/master/standards/.pylintrc#L91

Benjamin, there is no need to update all the code (unless we really want to), but please do update the code you're touching ;)

2019-01-22 09:57 UTC, amaltaro commented on src/python/WMCore/Services/StompAMQ/StompAMQ.py
> +                    'uuid': makeUUID()}
It doesn't make much difference for me either. @vkuznet @leggerf shall we keep uuid?

2019-01-22 09:59 UTC, amaltaro commented
Thanks, Benjamin! Just one more request from my side, can you please squash those commits in a single one? Thanks

2019-01-22 10:00 UTC, leggerf commented
I’d say let’s keep it. It doesn’t hurt


> On 22 Jan 2019, at 10:57, Alan Malta Rodrigues <notifications@github.com> wrote:
> 
> @amaltaro commented on this pull request.
> 
> In src/python/WMCore/Services/StompAMQ/StompAMQ.py <https://github.com/dmwm/WMCore/pull/8974#discussion_r249709813>:
> 
> > +               or not
> +
> +        :return: a list of notifications with the proper metadata
> +        """
> +        producer = producer or self._producer
> +        umetadata = metadata or {}
> +        ts = ts or int(time.time())
> +
> +        headers = {'type': docType,
> +                   'version': self._version,
> +                   'producer': producer}
> +
> +        metadata = {'timestamp': ts,
> +                    'producer': producer,
> +                    'id': docId,
> +                    'uuid': makeUUID()}
> It doesn't make much difference for me either. @vkuznet <https://github.com/vkuznet> @leggerf <https://github.com/leggerf> shall we keep uuid?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/dmwm/WMCore/pull/8974#discussion_r249709813>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AnhLQQXsv9hbT4SeU5ZBMHVi5j8KFkk1ks5vFuCBgaJpZM4aLACd>.
>

2019-01-22 10:08 UTC, stiegerb commented
Ok, squashed into one.

2019-01-22 13:53 UTC, stiegerb commented
There was still a typo, fixed now, and tested.

2019-01-22 14:09 UTC, vkuznet commented
Regarding docId vs uuid. This code does not provide any guarantee that docId will be unique since it is external parameter, i.e. it is up to applications which will call this module. Therefore my suggestion would be to keep uuid just in case because we are making it unique and therefore guarantee that submitted doc will have at least some unique id (either id or uuid).

2019-01-22 14:11 UTC, stiegerb commented
One more thing I noticed: we changed the name of the "id" field in the metadata to be "_id". Let me check with MONIT whether that's necessary for it to be picked up by them.

2019-01-22 14:13 UTC, stiegerb commented
@vkuznet yes, let's leave it for now. Although MONIT assigns a unique id to any incoming message anyway, so I'm not sure how useful it will be if we don't actually keep track of them anyway.

2019-01-23 11:35 UTC, stiegerb commented
Update from MONIT:
- If they find a field called "_id" or "metadata._id" in the data, they do **not** create a unique id. So maybe it would be good to keep ours, just in case.
- Indeed, id fields should be "_id", not "id". I'll update the PR to do so.
- The following list of fields are digested and promoted to metadata in the MONIT message. This means that if we want one of those fields to show up as a regular "data.x" field, we need to put it in a "data" subfield first. Otherwise it will be swallowed:
   - _id
   - availability_zone
   - environment
   - event_timestamp
   - host
   - hostgroup
   - hostname
   - json
   - path
   - producer
   - submitter_environment
   - submitter_hostgroup
   - toplevel_hostgroup
   - timestamp
   - timestamp_format
   - type
   - type_prefix
   - version

So it might be a good idea to keep our "payload" subfield, just renaming it to "data". We can make it configurable, so we can still use "payload" for backwards compatibility.

2019-01-24 09:39 UTC, leggerf commented
As it is, I don’t see any use for make_notification_list. What’s the argument to keep it?


> On 24 Jan 2019, at 10:26, Benjamin Stieger <notifications@github.com> wrote:
> 
> @vkuznet <https://github.com/vkuznet> @leggerf <https://github.com/leggerf> @amaltaro <https://github.com/amaltaro> Let's try to converge on this. I think the behavior of make_notification is ok now:
> 
> By default it packs the payload into a data subfield, which is swallowed by MONIT. For backwards compatibility people can change that to be called payload, or can omit it altogether (by passing an empty string or None).
> Users have to provide a type and id for each document which are written into the metadata. Maybe one could think of allowing users to omit the docId and then using the uuid also for the _id field, or for all of these to be taken from the provided metadata, but those are features we can leave also for future versions.
> Then I think the make_notification_list method should be either removed or should be calling make_notification internally. I know Alan disagrees, but as it is, this method doesn't make sense. It assigns the same docId, timestamp, and type to each document in the list. If we need a method that creates a list of notifications with the same type, timestamp, and metadata, we can do that by re-using the code in make_notification. But even then they should all have their own id.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/dmwm/WMCore/pull/8974#issuecomment-457126615>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AnhLQbQOHrvmbF-LD3A0It4_i02rjJa3ks5vGXwzgaJpZM4aLACd>.
>

2019-01-24 10:56 UTC, amaltaro commented
Argument against removing `make_notification_list` is:
* we might have service/nodes metrics that we want to push to MonIT where the document id itself does not matter; we'll never do anything with that same document besides making a time series plot (this is the case for WMAgent/ReqMgr2/Global Workqueue)
* in case of hundreds of thousands or millions of documents, calling `make_notification` for every single document increases the wallclock time by almost two orders of magnitude. You can check it yourself with this example:
https://github.com/amaltaro/ProductionTools/blob/master/timeFunctionCalls.py

`make_notification_list` method has two problems that I acknowledge. a) `producer` is actually overwritten somewhere in the MonIT ecosystem(?) and b) `docId`is wrong and we should replace `id` key/value by `_id: makeUUID()`.

However, if we want to make the code really clean, I think we can remove that method. The services I have pushing data to MonIT don't create more than 5k notifications every cycle, so I expect a performance impact closer to 0.

2019-01-24 13:23 UTC, stiegerb commented
@amaltaro In your example you're creating the data inside the loop, and calling time.time() every time. That's why it's so slow. If I rewrite it to just pass the data in the argument, calling the function multiple times is actually like 30% faster. See here: https://gist.github.com/stiegerb/6981b5487cb82483c08c85a5339a4a06

So I would propose to just remove the `make_notification_list` method. And in case no `docId` is provided, let's use the uuid, so users can fall back on that.

The last thing that Alan pointed out yesterday, the `send` method actually only accepts lists now and throws an error if a single notification is passed. I originally wrote it such that it internally converts it to a list with a single entry and sends it. Shall we revert to that or is there a good reason not to? Another reason to allow non-list data would be to allow generator objects.

2019-01-24 13:25 UTC, vkuznet commented
Now, when I look at full code I see few flaws in a logic:
- the module has 3 public APIs: send data, make notification and make notification list
- the send data API which handles N documents (where N is large) is very inefficient since our time is O(N) (we loop over every single notification and send one by one), see this line:
https://github.com/dmwm/WMCore/blob/783bd0447fe6e3cd14aa60704bdf1fb9288a75ed/src/python/WMCore/Services/StompAMQ/StompAMQ.py#L120
We should find out if there is a way to send a bulk of docs rather individual ones and adjust code accordingly if such API exists. Moreover the O(N) time is a network time rather the processing time.
- make_notification_list takes docId and then re-use it, see https://github.com/dmwm/WMCore/blob/783bd0447fe6e3cd14aa60704bdf1fb9288a75ed/src/python/WMCore/Services/StompAMQ/StompAMQ.py#L185 I doubt that we need documents with the same ids. Instead, my understanding that such API should not take docId and internally use makeUUID() to generate id of the documents.
- it also does not allow client to choose dataSubfield for documents and it means that it become useless as is if client wants to generate specific dataSubfield docs.
- but as an API it is useful for clients since they can only pass their documents and get notification docs.

2019-01-24 13:51 UTC, stiegerb commented
@vkuznet I remember checking whether there was a bulk send method in stomp. As far as I can tell there still isn't. However, I'm not sure it would make a difference, since we send data without waiting for acknowledgments. Note that we already open only a single connection for each list of documents we send. For reference, for the job monitoring data, we are sending bunches of 5000 docs in < 1 second. I don't think we're limited by the processing time inside StompAMQ here.

Shall I go ahead and update the PR to remove the `make_notification_list` method and to take the `_id` as the uuid in case it is not provided?

2019-01-24 15:00 UTC, amaltaro commented
> Shall I go ahead and update the PR to remove the make_notification_list method and to take the _id as the uuid in case it is not provided?

Yes, please go ahead.

2019-01-24 15:27 UTC, stiegerb commented
Ok, done and rebased to master. For me it's ready to be merged now, but maybe someone should have another look.

2019-01-24 15:46 UTC, vkuznet commented
@stiegerb , Benjamin thanks for providing benchmark, it answers my question. The code now looks good to me.

2019-01-25 17:11 UTC, amaltaro commented on src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py
> +            notifications = stompSvc.make_notification_list(payload=docs, docType=docType,
Benjamin, can you also update these 2 calls such that they reflect your changes to StompAMQ module?
Something like
```
notifications = []
for doc in docs:
    notifications.append(make_notification(payload=doc, docType=docType, ts=timeS, dataSubfield="payload"))
```

Same for the module below. Thanks

2019-01-25 21:14 UTC, amaltaro commented
Thanks, Benjamin. It should work, I'm just not sure I like it being a list comprehension with that for at the end of the 2nd line, it looks like the snippet I shared before is more readable.
Anyways, it's just my opinion and if needed to, I can update this code myself. Thanks

2019-01-28 09:36 UTC, amaltaro approved these changes

2019-01-28 09:37 UTC, amaltaro commented
Thanks, Benjamin. I ran a quick test and it works just fine.

2019-01-28 09:37 UTC, merged

2019-01-31 10:22 UTC, amaltaro commented on src/python/WMComponent/AgentStatusWatcher/AgentStatusPoller.py
> +            notifications = stompSvc.make_notification_list(payload=docs, docType=docType,
Sigh.. you missed the "dataSubfield" bit and I didn't catch it on my review either. Fixing it in a new PR