Use cmssw exit code from job report
dmwm/WMCore pull request #9009
Opened 2019-02-11 09:42 UTC by khurtado

Fixes #9006

2019-02-15 17:23 UTC, amaltaro requested changes
Kenyi, the logic seems to be correct. However, that function inside that method isn't very readable in my opinion.
I'd suggest to move that function `setStatus` to the top of the module (like analysisFileLFN), but then we have a problem with the CMSSW object reference... Which could be solved by making this method:
https://github.com/dmwm/WMCore/blob/43130ef1d7c63cb56c09f542f1fca8732f880412/src/python/WMCore/WMSpec/Steps/Executor.py#L165

a function. What do you think?

2019-02-15 17:37 UTC, khurtado commented
> Kenyi, the logic seems to be correct. However, that function inside that method isn't very readable in my opinion.
> I'd suggest to move that function `setStatus` to the top of the module (like analysisFileLFN), but then we have a problem with the CMSSW object reference... Which could be solved by making this method:
> [WMCore/src/python/WMCore/WMSpec/Steps/Executor.py](https://github.com/dmwm/WMCore/blob/43130ef1d7c63cb56c09f542f1fca8732f880412/src/python/WMCore/WMSpec/Steps/Executor.py#L165)
> 
> Line 165 in [43130ef](/dmwm/WMCore/commit/43130ef1d7c63cb56c09f542f1fca8732f880412)
> 
>  def setCondorChirpAttrDelayed(self, key, value): 
> a function. What do you think?

What about
`self.step.execution.exitStatus` ?

2019-02-15 19:57 UTC, amaltaro commented
Thanks, Kenyi. That's fine too, I was only concerned that it breaks the Executor interface definition. But I think it's Ok.
Can you test these new changes again? I'll run a final test on Monday and if everything is fine, we can backport it to 1.1.20_wmagent branch

2019-02-18 00:55 UTC, khurtado commented
@amaltaro Tested new changes and everything seemed fine.

2019-02-20 08:54 UTC, amaltaro commented
Something doesn't match here. The code looks fine, but the error report in WMStats is a bit weird.
In WMStats job detail view, the "error message" column should contain something like `FileReadError`, not "Error running cmsRun {'arguments': ['/bin/bash', '/srv/job/WMTaskSpace/cmsRun1/cmsRun1-main.sh', '', u'slc6_amd64_gcc700', 'scramv1', 'CMSSW', 'CMSSW_10_2_4_patch1', 'FrameworkJobReport.xml', 'cmsRun', 'PSet.py', '', '', '']} CMSSW Return code: 8021 ,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,Fatal Exception,ReportManipulatingError,WMAgentStepExecutionError".

Without mentioning other problems related to error handling in WMCore that are not related to your fix. Let me try a few things...

2019-02-20 12:00 UTC, amaltaro commented
You kept the same logic for raising a WMExecutionFailure exception. I don't get why I've never seen those long error messages in wmstats.

2019-02-20 13:28 UTC, amaltaro approved these changes

2019-02-20 13:29 UTC, amaltaro commented
Let's worry about the error handling and the amount of errors at a later stage. Backporting it and pushing it in in all the new agents. Thanks, Kenyi!

2019-02-20 13:33 UTC, merged

2019-02-20 15:54 UTC, amaltaro commented
@stiegerb you should start seeing the correct CMSSW exit codes getting chirped to the schedd.
Is there any expected change from your side? Or that classad is already taken care of by your script?