Fix issue with missing received bytes in custom cherrypy logger (used by DBS)
dmwm/WMCore pull request #9169
Opened 2019-04-29 15:54 UTC by vkuznet

2019-04-29 15:54 UTC, vkuznet commented
@yuyiguo , please try it out and let us know if it fixes the missing input bytes in cherrypy logger messages.

2019-04-29 16:30 UTC, yuyiguo commented
@vkuznet 
Below os the DBS version of Root.py. It seemed that you patch a different one. 
https://github.com/dmwm/WMCore/blob/1.1.16_dbs/src/python/WMCore/WebTools/Root.py

2019-04-29 16:38 UTC, vkuznet commented
Yuyi, I always patch master head and not specific branches. If you need a specific branch you can do it on your own based on changes I provided here.

2019-04-29 16:46 UTC, yuyiguo commented
@vkuznet 
They are very different code.

2019-04-29 16:55 UTC, vkuznet commented
Yuyi,
how this line
https://github.com/dmwm/WMCore/blob/1.1.16_dbs/src/python/WMCore/WebTools/Root.py#L86
is different from this one
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WebTools/Root.py#L92

I understand that they are on different line numbers in your editor. But the code is identical.

What I fixed is replaced `-` with `%(i)s` and define what `i` would mean and passed to the string.

Again, look at the code, take parts which I defined in master head, and put it into your branch.

2019-04-29 17:13 UTC, yuyiguo commented
@vkuznet 
Sorry that was my mistake. The difference was from other places before the patch part.

2019-04-29 17:38 UTC, yuyiguo commented
@vkuznet 
Here is the output [data:  503n 2 out 508369 us ] 

Not sure why the work "in" was cut half?

2019-04-29 17:46 UTC, yuyiguo commented
@vkuznet 
For the get calls, it only show "INFO:cherrypy.access:REQUEST",  the information("INFO:cherrypy.access") after the request processed was missing.

2019-04-29 17:52 UTC, vkuznet commented
Yuyi, the missing `in` in `[data: 503n 2 out 508369 us ]` was due to bug in string format. I updated PR, originally I put `%(i)` but it should be `%(i)s`.

2019-04-29 17:52 UTC, vkuznet commented
please try now with updated PR.

2019-04-29 18:13 UTC, yuyiguo commented
@vkuznet 
How about the missing info for the GET calls?

2019-04-29 18:15 UTC, vkuznet commented
it is unclear from your messages what's wrong with GET messages. Please post example of POST and GET messages.

2019-04-29 18:23 UTC, yuyiguo commented
@vkuznet 

It works for POST now. GET is missing the info after processed.

 "if not rbytes:" was two times? Not sure which one is the GTE case?

2019-04-29 18:38 UTC, vkuznet commented
Yuyi, just post GET and POST messages.

The two if statements because request/body size can be calculated differently. I put all three methods. The GET method does not have a body so I would assume it should get zero rbytes.

2019-04-29 19:11 UTC, yuyiguo commented
@vkuznet 
See below example [1] of a GET call to DBS before today's patch. I remove some of the info for security reason. There are two parts: 
The first one "INFO:cherrypy.access:REQUEST " is the request info. This part was added recently.
The second one "INFO:cherrypy.access" is the log of the request served by DBS.  This is the old DBS log since one day. It also has [data: - in 54 out 862 us ] part.

Now we missed the second one after today's patch.


[1]
" INFO:cherrypy.access:REQUEST [28/Apr/2019 00:33:53 GMT] 188.184.93.2 56510 GET /serverinfo 'User-Agent': 'DBSClient/3.7.8/', 'Cms-Authz-Developer': 'group:reqmgr', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Server': 'cmsweb-testbed.cern.ch', 'Content-Type':
 'application/json', 'Cms-Request-Uri': '/dbs/int/global/DBSReader//serverinfo'}] [] [{}]

INFO:cherrypy.access:[28/Apr/2019:02:33:53] vocms0132.cern.ch 188.184.93.2 "GET /dbs/int/global/DBSReader/serverinfo HTTP/1.1" 200 OK [data: - in 54 out 862 us ] [auth: OK " ] [ref: "" "DBSClient/3.7.8/" ]

2019-04-29 19:37 UTC, vkuznet commented
Yuyi,
GET request does not have a body and there is no in info. But I updated PR one
more time to protect code from this case when there is such info.

Please test it again.

We may dump bytes info in REQUEST as well I think if we can extract
Content-Length HTTP parameter from cherrypy.request. But for that I prefer to
have separate PR.


On  0, Yuyi Guo <notifications@github.com> wrote:
> @vkuznet 
> See below example [1] of a GET call to DBS before today's patch. I remove some of the info for security reason. There are two parts: 
> The first one "INFO:cherrypy.access:REQUEST " is the request info. This part was added recently.
> The second one "INFO:cherrypy.access" is the log of the request served by DBS.  This is the old DBS log since one day. It also has [data: - in 54 out 862 us ] part.
> 
> Now we missed the second one after today's patch.
> 
> 
> [1]
> " INFO:cherrypy.access:REQUEST [28/Apr/2019 00:33:53 GMT] 188.184.93.2 56510 GET /serverinfo 'User-Agent': 'DBSClient/3.7.8/', 'Cms-Authz-Developer': 'group:reqmgr', 'X-Forwarded-Proto': 'https', 'X-Forwarded-Server': 'cmsweb-testbed.cern.ch', 'Content-Type':
>  'application/json', 'Cms-Request-Uri': '/dbs/int/global/DBSReader//serverinfo'}] [] [{}]
> 
> INFO:cherrypy.access:[28/Apr/2019:02:33:53] vocms0132.cern.ch 188.184.93.2 "GET /dbs/int/global/DBSReader/serverinfo HTTP/1.1" 200 OK [data: - in 54 out 862 us ] [auth: OK " ] [ref: "" "DBSClient/3.7.8/" ]
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/9169#issuecomment-487706278

2019-04-30 13:54 UTC, vkuznet commented
@amaltaro , Alan please review the changes as it requires to see dump of DBS incoming requests info and related to ongoing investigation. It would be nice to have these changes in place for next cmsweb upgrade (my understanding that Yuyi will patch separate branch, but if she did we should keep these changes in master head too).

2019-04-30 14:24 UTC, amaltaro commented
@vkuznet when your' PR is ready for review, please use the top-right option "Reviewers" to ask for reviews.

2019-04-30 14:38 UTC, amaltaro requested changes
Just some aesthetic changes that can be made, otherwise it looks Ok.

2019-04-30 14:38 UTC, amaltaro commented on src/python/WMCore/WebTools/Root.py
> +        if 'Content-Length' in cherrypy.request.headers:
Given that you assign `cherrypy.request` to `request`, you can replace all those places like this line and a few others below.

2019-04-30 17:57 UTC, yuyiguo commented
@vkuznet 
Valentin,

I was testing on cmsweb-testbed and found that the missing log on GET after processing actually happened before this PR. I don't know when this started since I just realized this yesterday. I did not see any errors in the log. Could you take a look at previous PR ? I will continue to test this PR, but I double the missing log will come back with this updated PR.

2019-04-30 18:09 UTC, vkuznet commented
Yuyi, I'm not sure I understand what you're saying. Please rephrase where the problem and/or give examples.

2019-04-30 18:44 UTC, yuyiguo commented
@vkuznet 
Sorry Valentin, that was  my reading error.  I did not get the log because I got an " HTTP Error 502: Proxy Error".  This was first time that I got 502 on a cmsweb-testbed. I ran 300 unit tests in a single thread and one of the tests got 502 error. It is wired and not sure what I should look into.  I will check the FE log, but not sure I will find anything useful. 

The unit tests kind of ran slower than I thought. I am not sure why. Will rerun it.

2019-04-30 19:27 UTC, yuyiguo commented
Here is the query that I got 502 error. 
DBS server log:
```
INFO:cherrypy.access:REQUEST [30/Apr/2019 17:24:50 GMT] 188.184.94.167 53222 GET /blockdump [{'Cms-Authn-Name': 'Yuyi Guo','Accept': 'application/json', 'X-Forwarded-For': '188.184.94.167', 'Cms-Authn-Login': 'yuyi', 'Host': 'vocms0731.cern.ch:8252', 'User-Agent': 'DBSClient/3.7.8.2/', 'X-Forwarded-Server': 'testbed.cern.ch', 'Content-Type': 'application/json', 'Cms-Request-Uri': '/dbs/int/global/DBSReader/blockdump?block_name=%2Funittest_web_primary_ds_name_24607%2Facq_era_24607-v4609%2FGEN-SIM-RAW%2324607'}] [block_name=%2Funittest_web_primary_ds_name_24607%2Facq_era_24607-v4609%2FGEN-SIM-RAW%2324607] [{'block_name': u'/unittest_web_primary_ds_name_24607/acq_era_24607-v4609/GEN-SIM-RAW#24607'}]
```
As you can see the "block_name" was repeated twice.

Then what I got from front end access log is
```
[30/Apr/2019:19:24:50 +0200] cmsweb-testbed.cern.ch 188.184.94.167 "GET /dbs/int/global/DBSReader/blockdump?block_name=%2Funittest_web_primary_ds_name_24607%2Facq_era_24607-v4609%2FGEN-SIM-RAW%2324607 HTTP/1.1" 502 [data: 7164 in 15988 out 475 body 300088217 us ] [auth: TLSv1.2 ECDHE-RSA"/DC=ch/DC=cern/OU=Organic Units/OU=" "-" ] [ref: "-" "DBSClient/3.7.8.2/" ]
```
This blockdump took 300.088217 seconds and I guess this cause the http 502 error. 
I think I used to get timeout error instead of 502 error.  Any reason for this change? I feel the timeout is more clear message than 502.

2019-04-30 20:36 UTC, vkuznet commented
Yuyi,
both issues are not related to this PR.

The first one is related to this PR:
https://github.com/cms-sw/cmsdist/pull/4922
see
https://github.com/dmwm/WMCore/pull/9124/files#diff-27caaae36aa502e2719c31060d1bfa8fR190
and
https://github.com/dmwm/WMCore/pull/9124/files#diff-27caaae36aa502e2719c31060d1bfa8fR190

The first one is request.query_string and second block name is from
request.params

It is up to you to decide if you want to keep both. If one of them should be
dropped we need another PR.

The second issue you reported here, time out, has nothing to do with proposed
changes.

Therefore I don't know if I need to address anything here.

Best,
Valentin.

On  0, Yuyi Guo <notifications@github.com> wrote:
> Here is the query that I got 502 error. 
> DBS server log:
> ```
> INFO:cherrypy.access:REQUEST [30/Apr/2019 17:24:50 GMT] 188.184.94.167 53222 GET /blockdump [{'Cms-Authn-Name': 'Yuyi Guo','Accept': 'application/json', 'X-Forwarded-For': '188.184.94.167', 'Cms-Authn-Login': 'yuyi', 'Host': 'vocms0731.cern.ch:8252', 'User-Agent': 'DBSClient/3.7.8.2/', 'X-Forwarded-Server': 'testbed.cern.ch', 'Content-Type': 'application/json', 'Cms-Request-Uri': '/dbs/int/global/DBSReader/blockdump?block_name=%2Funittest_web_primary_ds_name_24607%2Facq_era_24607-v4609%2FGEN-SIM-RAW%2324607'}] [block_name=%2Funittest_web_primary_ds_name_24607%2Facq_era_24607-v4609%2FGEN-SIM-RAW%2324607] [{'block_name': u'/unittest_web_primary_ds_name_24607/acq_era_24607-v4609/GEN-SIM-RAW#24607'}]
> ```
> As you can see the "block_name" was repeated twice.
> 
> Then what I got from front end access log is
> ```
> [30/Apr/2019:19:24:50 +0200] cmsweb-testbed.cern.ch 188.184.94.167 "GET /dbs/int/global/DBSReader/blockdump?block_name=%2Funittest_web_primary_ds_name_24607%2Facq_era_24607-v4609%2FGEN-SIM-RAW%2324607 HTTP/1.1" 502 [data: 7164 in 15988 out 475 body 300088217 us ] [auth: TLSv1.2 ECDHE-RSA"/DC=ch/DC=cern/OU=Organic Units/OU=" "-" ] [ref: "-" "DBSClient/3.7.8.2/" ]
> ```
> This blockdump took 300.088217 seconds and I guess this cause the http 502 error. 
> I think I used to get timeout error instead of 502 error.  Any reason for this change? I feel the timeout is more clear message than 502.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/dmwm/WMCore/pull/9169#issuecomment-488083343

2019-05-01 03:03 UTC, yuyiguo commented
@vkuznet 
Valentin, 
In this example, request.query_string and request.params are the same.  I am not sure when they will be different? 
For the message of timeout error or not, I knew it is not related to this PR.  I mentioned here in case you or @amaltaro would knew the change of error message.

2019-05-01 05:27 UTC, amaltaro commented
Yuyi, cmsweb frontend time out has always returned a Proxy Error. We've already discussed that it's not the best error message, and I believe Diego G. explained me the reason behind that (or why they cannot change it). I no longer remember it since it was many years ago. I think we can simply disregard it and take a `502 Proxy Error` as a frontend timeout.

2019-05-01 12:19 UTC, vkuznet commented
Yuyi, here is new PR which removes query string:
https://github.com/dmwm/WMCore/pull/9171

And, I agree with Alan regarding `502` error. I'm not sure where it is exactly generated and if it is in internals of CherryPy we better not to touch it, if it is returned by FE we also better not to touch it.

2019-05-01 12:58 UTC, amaltaro commented
Yuyi, if you're somewhat happy with this patch, let me know and I can backport it to the dbs branch such that you can cleanly apply this patch and run your final tests.

2019-05-01 15:20 UTC, yuyiguo commented
@vkuznet @amaltaro 
Thanks for the explanation. I will do one more testing before we commit it.

2019-05-03 13:46 UTC, amaltaro commented
New fix in #9177

2019-05-03 13:46 UTC, closed without merging