Correct reference to blocksize in PrimaryBlocks && Catch exception while calling makeTransferRequest in MSTrasferor
dmwm/WMCore pull request #9552
Opened 2020-03-12 05:25 UTC by todor-ivanov

Fixes #9551

#### Status
not-tested

#### Description
Fixing the bug with the wrong reference to the 'blockSize' when trying to get PrimaryBlocks in Workflow.py and also catching any exception that  may be thrown while calling makeTransferRequest in MSTransferor.py. The exception is handled in a per workflow basis and only for that function call, so that the cycle is not interrupted and also later in the same iteration the success/failure counters could be updated.    

#### Is it backward compatible (if not, which system it affects?)
YES

#### Related PRs
None

#### External dependencies / deployment changes
None

2020-03-12 18:00 UTC, amaltaro requested changes
A couple of comments in the code that should make it slightly better.

2020-03-12 18:00 UTC, amaltaro commented on src/python/WMCore/MicroService/Unified/MSTransferor.py
> +                    msg += "\nError: %s" % str(ex)
In order to keep things on the same line. Can you replace `\n` by `\t`?

2020-03-12 19:16 UTC, todor-ivanov commented
@amaltaro  all requested changes are done. You may check it again now.

2020-03-14 21:31 UTC, amaltaro commented
@todor-ivanov Todor, I found a few more errors while testing this patch. Can you please apply the following changes from a local diff:
```
amaltaro@alancc7-cloud1:/data/srv/current $ diff -rup Workflow.py /data/srv/HG2003k/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.1.pre3/lib/python2.7/site-packages/WMCore/MicroService/DataStructs/Workflow.py
--- Workflow.py	2020-03-14 22:07:24.238310420 +0100
+++ /data/srv/HG2003k/sw/slc7_amd64_gcc630/cms/reqmgr2ms/0.2.1.pre3/lib/python2.7/site-packages/WMCore/MicroService/DataStructs/Workflow.py	2020-03-14 22:29:28.627473259 +0100
@@ -329,6 +329,8 @@ class Workflow(object):
             return [thisChunk], [thisChunkSize]
 
         # create a descendant list of blocks according to their sizes
+        # sortedPrimary structure is a list of tuples, such as:
+        # [('block_name_XXX', {'blockSize': 123, 'locations': ['XXX', 'YYY']}), ('block_name_YYY', {'blockSize': 345, 'locations': ['YYY']})]
         sortedPrimary = sorted(self.getPrimaryBlocks().items(), key=operator.itemgetter(1), reverse=True)
         chunkSize = sum(item[1]['blockSize'] for item in sortedPrimary) // numChunks
 
@@ -347,9 +349,9 @@ class Workflow(object):
                 if not sortedPrimary or idx >= len(sortedPrimary):
                     # then all blocks have been distributed
                     break
-                elif thisChunkSize + sortedPrimary[idx][1] <= chunkSize:
+                elif thisChunkSize + sortedPrimary[idx][1]['blockSize'] <= chunkSize:
                     thisChunk.add(sortedPrimary[idx][0])
-                    thisChunkSize += sortedPrimary[idx][1]
+                    thisChunkSize += sortedPrimary[idx][1]['blockSize']
                     sortedPrimary.pop(idx)
                 else:
                     idx += 1
@@ -360,7 +362,7 @@ class Workflow(object):
         while sortedPrimary:
             for chunkNum in range(numChunks):
                 blockChunks[chunkNum].add(sortedPrimary[0][0])
-                sizeChunks[chunkNum] += sortedPrimary[0][1]
+                sizeChunks[chunkNum] += sortedPrimary[0][1]['blockSize']
                 sortedPrimary.pop(0)
                 if not sortedPrimary:
                     break
```

2020-03-16 03:47 UTC, todor-ivanov commented
@amaltaro 
DONE

2020-03-16 09:47 UTC, amaltaro commented
Thanks, Todor.
Unfortunately I found a couple other issues that I'm trying to address in a new PR
https://github.com/dmwm/WMCore/pull/9560

so we will likely close this one later.

2020-03-17 20:57 UTC, amaltaro commented
The other PR has just been merged, so I'm closing this one. Thanks Todor!

2020-03-17 20:57 UTC, closed without merging