PY3: Properly deal with strings in REST/Main
dmwm/WMCore pull request #9871
Opened 2020-08-14 14:39 UTC by amaltaro

Fixes #9794 

#### Status
ready

#### Description
I'm still debugging the rucio initialization problem, but there seems to be no issue.
This PR fixes the unicode / string issue reported in the traceback. The traceback is a python2 string, so we need to use BytesIO instead of StringIO.

#### Is it backward compatible (if not, which system it affects?)
yes

#### Related PRs
None

#### External dependencies / deployment changes
None

2020-08-14 16:01 UTC, amaltaro commented
test this please

2020-08-14 22:15 UTC, amaltaro commented
test this please

2020-08-15 18:03 UTC, amaltaro commented
test this please

2020-08-17 13:22 UTC, mapellidario requested changes
Dear Alan, the change that you propose would work in python2 only, it would brake in python3.

I did some tests with`traceback` and `io` at

* py2: https://cms-dmwm-test.docs.cern.ch/py2py3/porting/traceback_py2/
* py3: https://cms-dmwm-test.docs.cern.ch/py2py3/porting/traceback_py3/

Why is this the case? Prerequisites

1. `StringIO.StringIO` constructor accepts both unicode and bytes strings. Available only in py2
1. `io.StringIO` constructor accepts _only_ unicode strings in both py2 and py3 (backported in py2 from py3. This is why "String" in `StringIO` (unicode sequence) differs from the type `str` (bytes sequence))
1. `io.BytesIO` constructor accepts _only_ bytes strings in both py2 and py3 (backported in py2 from py3)
1. `traceback.print_exc(file=trace)` in py2 internally does directly `trace.write(stacktrace)`, where `stacktrace` is a `str`, which in py2 is a sequence of bytes.
1. `traceback.print_exc(file=trace)` in py3 internally writes to the file with `print(line, file=trace)`. python3 [print](https://docs.python.org/3/library/functions.html#print) converts all the inputs to `str` before writing to the buffer, and in python3 `str` is a sequence of unicode codepoints.

What can be done:
* py2: use `trace = StringIO.StringIO()`
* py2: use `trace = io.BytesIO()`
* py3: use `trace = io.StringIO()`

Some more tests with `io.StringIO` and `io.BytesIO`

* https://cms-dmwm-test.docs.cern.ch/py2py3/porting/strings_io_py2/
* https://cms-dmwm-test.docs.cern.ch/py2py3/porting/strings_io_py3/

2020-08-17 13:22 UTC, mapellidario commented on src/python/WMCore/REST/Main.py
> +            trace = BytesIO()
```suggestion
            import sys
            [...]
            if sys.version[0] == '2':
                trace = BytesIO()
            elif sys.version[0] == '3':
                tracce = StringIO()
```

2020-08-17 13:31 UTC, amaltaro commented
Thank you very much for this deep review, Dario.
An alternative to your suggestion, how about we import different classes but with the same name (such that all the changes are made at import level instead of in the middle of the code)? Something like:
```
if sys.version[0] == '2':
                from io import BytesIO as StringIO
else:
                from io import StringIO
```

2020-08-17 13:47 UTC, mapellidario commented
Yes, that would work, too. 

However, we can consider this an exercise for the gradual migration of WMCore. What if we have module A.py with ` from io import BytesIO as StringIO`, and module B.py that imports A.py but require `from io import StringIO` ? Renaming modules is fine if we have isolated modules, but I fear that in the long run it could cause problems. Moreover, since during the migration we will have to deal with such errors a lot, I would prefer to be 100% sure of the type of a variable reading only the line where it is defined. I fear that if we rename modules, then I will make some mess since I forget to check at the beginning of the file if an imported module has been renamed. I know that the expense is less beautiful code, but in this case I would trade less beauty for more clarity. 

This being said, code style is a matter of opinions, and your opinion always has the priority

2020-08-17 15:35 UTC, amaltaro commented
I did some local tests and it would only be a problem if we had (not recommended!) imports like:
```
from A import *
```

then those modules would be at the main scope of the imported modules.
While, if one does imports like
```
import A
import B
```
this would be completely fine and `StringIO` (or the masked BytesIO) would be in the scope of the module A (or module B).

The motivation I had to have this py2/py3 logic in the imports section is that when deprecating py2, it would be mostly a matter of imports, without touching the internals of the code.
However, I do agree with you that - if we have problems due to this masked importing - things will be much harder to debug. I'm going to apply your suggestion soon. Thanks again Dario!

2020-08-18 08:23 UTC, amaltaro commented
@mapellidario I have updated this PR following your suggestion, could you please review it once again?

In addition to this, I guess we should revisit all the usage of BytesIO and implement the same logic we have in this PR. Would you see any possible exception to that?

2020-08-18 09:52 UTC, mapellidario approved these changes
This looks perfect to me!
I know that this may look like a bit cumbersome, but it the best that we can do while maintaining py2 and py3 correctness and code clarity. 
Thanks Alan!

2020-08-18 09:58 UTC, mapellidario commented
Well, I would be a bit more conservative and would not jump into applying the same logic everywhere. The solution that we found for this case depends on the interface of `traceback`, which maintained `str` in both py2 and py3 despite its change of meaning. A different library could choose a different approach and the only way to be sure is to check it case by case. 
Since dealing with strings is the most difficult and troublesome part of the migration, I would leave every aspect of it to the gradual migration. If it were not for your open PR, I would not have suggested any change to this module right now.

2020-08-18 10:14 UTC, amaltaro commented
Sounds good. Thanks for your feedback, Dario.
This has been tested on my VM (py2, of course) and it works fine.

2020-08-18 10:14 UTC, merged